(()=>{
 'use strict';
 const A=Avian,$=id=>document.getElementById(id),world=new A.World(),audio=new Soundscape(),renderer=new AvianRenderer($('scene'),$('map'),$('spectrum'));
 const state={started:false,paused:false,yaw:0,mode:'optical',zoom:false,selected:null,evidence:new Map(),prediction:null,pending:null,records:[],signalSignature:'',lastSequence:0,lastUI:0};
 const storageKey='avian-os.records.v1';let toastTimer=0,last=performance.now(),pointer=null;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),5000);}
 try{const saved=JSON.parse(localStorage.getItem(storageKey)||'[]');if(Array.isArray(saved))state.records=saved.filter(r=>r&&typeof r.id==='string'&&(A.byId[r.species]||r.species==='nonbird')&&Array.isArray(r.evidence)).slice(-200);}catch{toast('本地档案暂时不可用，本次仍可观测并导出。');}
 function evidence(){return state.evidence.get(state.selected)||[];}
 function isFrozen(){return $('field-view').hidden||!state.started||state.paused||document.hidden||!!document.querySelector('dialog[open]');}
 function syncAudio(){audio.pause(isFrozen()).catch(()=>{});}
 function currentPrior(){const ev=evidence().find(e=>e.key==='context');return ev?.minute??world.minute;}
 function renderInference(){const es=evidence().filter(e=>e.key!=='context'),post=A.infer(es,currentPrior());$('candidates').innerHTML=post.map(c=>`<div class="candidate"><div class="candidate-line"><span>${c.name}</span><span>${c.prob<.01?'&lt;1':c.prob>.99?'&gt;99':Math.round(c.prob*100)}<small>%</small></span></div><div class="candidate-track"><i style="width:${c.prob*100}%"></i></div></div>`).join('');$('inference-title').textContent=state.selected?'信号 '+state.selected.toUpperCase()+(es.some(e=>e.key==='visual')?' / 已目视':' / 待验证'):'环境先验 · 未锁定';$('evidence-count').textContent=es.length+' / 4 证据';$('evidence').innerHTML=es.length?es.map(e=>`<div>✓ ${esc(e.label)}${e.at?` <span class="tiny">${esc(e.at)}</span>`:''}</div>`).join(''):'<span>选择一个信号，开始缩小可能性。</span>';
  const top=A.byId[post[0].id];$('prediction-hint').textContent=es.length&&top?`${top.name}目前领先，但仍待验证。${top.habits}`:'听到信号以后，先想想它可能在什么环境活动。';
  document.querySelectorAll('.sensor-actions button').forEach(b=>b.disabled=!state.selected||!state.started);
 }
 function selectSignal(id,event){state.selected=id;if(!state.evidence.has(id))state.evidence.set(id,[{key:'context',minute:world.minute}]);state.yaw=event.bearing;state.signalSignature='';renderInference();toast('已粗略转向声源。采集声纹和栖息地，比较概率的变化。');}
 function renderSignals(){const recent=world.events.filter((ev,i,list)=>list.findIndex(x=>x.entityId===ev.entityId)===i).slice(0,5);const sig=recent.map(e=>e.id).join()+state.selected;if(sig===state.signalSignature)return;state.signalSignature=sig;$('signal-count').textContent=String(recent.length).padStart(2,'0')+' LIVE';$('signals').innerHTML=recent.length?recent.map(e=>`<button class="signal ${state.selected===e.entityId?'active':''}" data-signal="${e.id}"><span class="signal-wave">${e.label.includes('声纹')?'⌁':'∿'}</span><span class="signal-main">${e.label}<small>信号 ${e.entityId.toUpperCase()} · ${e.strength>.5?'近 / 中距':'较远'} · 方位约值</small></span><span class="bearing">${String(Math.round((e.bearing+360)%360)).padStart(3,'0')}°</span></button>`).join(''):'<div class="empty">暂时没有新信号。<br><small>静候、换观察点，或试试清晨与傍晚。</small></div>';recent.forEach(e=>document.querySelector(`[data-signal="${e.id}"]`)?.addEventListener('click',()=>selectSignal(e.entityId,e)));}
 function setMode(mode){state.mode=mode;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));const labels={optical:'OPTICAL / '+(state.zoom?'6.0×':'广角'),mic:'AUDIO / 定向聆听',thermal:'THERMAL / 热源扫描',eyes:'EYES CLOSED / 仅声音'};$('mode-label').textContent=labels[mode];$('viewport').classList.toggle('eyes',mode==='eyes');if(mode==='eyes')toast('闭上眼睛。拖动转向，让耳机里的声源逐渐靠近中央。');}
 function zoom(){state.zoom=!state.zoom;$('zoom').classList.toggle('selected',state.zoom);$('zoom').textContent=state.zoom?'1× 返回广角':'6× 望远镜';setMode(state.mode);}
 function scan(modality){
  if(!state.started){toast('先点击「开始观测」。');return;}if(!state.selected){toast('先选择右侧一条环境信号。');return;}
  if(modality==='visual'&&(state.mode!=='optical'||!state.zoom)){setMode('optical');if(!state.zoom)zoom();toast('已打开望远镜。水平对准目标后，再点一次「目视确认」。');return;}
  if(modality==='audio')setMode('mic');if(modality==='thermal')setMode('thermal');
  const result=world.observe(state.selected,modality,state.yaw);if(!result.ok){toast(result.reason);return;}
  result.evidence.at=A.formatTime(world.minute);result.evidence.day=world.day;result.evidence.station=world.player.name;
  const before=A.infer(evidence().filter(e=>e.key!=='visual'),currentPrior());state.evidence.set(state.selected,A.putEvidence(evidence(),result.evidence));renderInference();
  if(modality==='audio'){audio.play({entityId:state.selected},world,state.yaw,true);$('spectrum-caption').textContent='采样约 '+result.evidence.pitch+' Hz · 含环境噪声';}
  if(result.confirmed){
   const b=world.entity(state.selected),s=A.byId[result.confirmed];const pred=state.prediction&&state.prediction.entity===state.selected?{...state.prediction,actual:b.habitat,correct:state.prediction.habitat===b.habitat}:null;
   state.pending={id:globalThis.crypto?.randomUUID?.()||String(Date.now()),species:result.confirmed,object:s?s.name:A.noiseNames[b.type],day:world.day,time:A.formatTime(world.minute),station:world.player.name,weather:world.env.name,habitat:A.habitats.find(h=>h.id===b.habitat).name,evidence:evidence().filter(e=>e.key!=='context').map(e=>({...e})),before:before.map(c=>({name:c.name,prob:c.prob})),prediction:pred,note:'',createdAt:new Date().toISOString()};
   $('record-name').textContent=s?s.name:'假信号，也是一条发现';$('record-description').textContent=s?`${s.shape}。${before[0].id!==s.id?'目视证据推翻了模型之前的第一候选。':'这一次，视觉细节支持了你的判断。'}`:`你看到的是${A.noiseNames[b.type]}。把误判记下来，下次会更敏锐。`;
   $('record-meta').textContent=`DAY ${world.day} · ${A.formatTime(world.minute)} · ${world.player.name} · ${state.pending.habitat}`+(pred?` / 栖息地预测${pred.correct?'吻合':'未吻合'}`:'');$('note').value='';$('record-art').innerHTML='<canvas width="700" height="240"></canvas>';const canvas=$('record-art').firstChild;if(s)drawAvianBird(canvas.getContext('2d'),s,350,125,28);else{const c=canvas.getContext('2d');c.fillStyle='#e6a476';c.font='70px serif';c.textAlign='center';c.fillText('?',350,150);}
   $('record-dialog').showModal();syncAudio();
  }else toast(result.evidence.label+'。候选概率已更新。');updateMission();
 }
 function updateMission(){const es=evidence();const done=[es.some(e=>e.key==='audio'),es.some(e=>e.key==='habitat'),!!state.prediction,state.records.some(r=>r.species!=='nonbird')];[...$('mission-progress').children].forEach((el,i)=>el.classList.toggle('done',done[i]));const found=new Set(state.records.filter(r=>r.species!=='nonbird').map(r=>r.species));if(found.size){$('mission-title').textContent='慢慢认识这片湿地 · '+found.size+' / 6';$('mission-text').textContent=found.size===6?'六种鸟都留下了目视记录。换个时段，再看一次它们的生活。':'夜鹭在白天常被树冠遮住。黎明或傍晚，再去林间听听。';}}
 function renderJournal(){const birds=new Set(state.records.filter(r=>r.species!=='nonbird').map(r=>r.species)),falseCount=state.records.filter(r=>r.species==='nonbird').length;$('record-count').textContent=String(state.records.length).padStart(2,'0');$('journal-stats').innerHTML=`<div><b>${birds.size} / 6</b><span>已确认物种</span></div><div><b>${state.records.length}</b><span>完整现场记录</span></div><div><b>${falseCount}</b><span>已排除假信号</span></div>`;
  $('journal-list').innerHTML=state.records.length?[...state.records].reverse().map(r=>`<article class="panel record-card"><span class="stamp">${r.species==='nonbird'?'假信号已排除':'目视已确认'}</span><div class="record-date">DAY ${esc(r.day)} / ${esc(r.time)}</div><h2>${esc(r.object)}</h2><small>${esc(r.station)} · ${esc(r.weather)} · ${esc(r.habitat)}</small><p>${r.evidence.map(e=>esc(e.label)).join('<br>')}</p>${r.prediction?`<p>预测${r.prediction.correct?'吻合':'未吻合'}：${esc(A.habitats.find(h=>h.id===r.prediction.habitat)?.name)} → ${esc(A.habitats.find(h=>h.id===r.prediction.actual)?.name)}</p>`:''}<p>${esc(r.note||'没有附加笔记。')}</p><small>确认前领先候选：${esc(r.before?.[0]?.name||'未记录')} ${Math.round((r.before?.[0]?.prob||0)*100)}%</small></article>`).join(''):'<div class="panel journal-empty">还没有完整记录。<br>先捕获一个声音，让它引你看见第一只鸟。<br><small>档案保存在当前浏览器；重要记录可导出 JSON。</small></div>';updateMission();
 }
 function setTab(name){$('toast').classList.remove('show');clearTimeout(toastTimer);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));['challenge','field','journal','guide'].forEach(t=>$(t+'-view').hidden=t!==name);if(name==='journal')renderJournal();if(name==='guide')document.querySelectorAll('.guide-bird').forEach(canvas=>{const {width:w,height:h}=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;const c=canvas.getContext('2d');c.scale(d,d);drawAvianBird(c,A.byId[canvas.dataset.bird],w*.5,h*.59,17);});syncAudio();document.dispatchEvent(new CustomEvent('avian:tab',{detail:name}));}
 function changeStation(id){if(id===world.player.id)return;world.moveStation(id);state.yaw=world.player.yaw;state.selected=null;state.signalSignature='';$('station-label').textContent=world.player.name;document.querySelectorAll('[data-station]').forEach(b=>b.classList.toggle('selected',b.dataset.station===id));$('prediction-status').textContent=state.prediction?'已保留信号 '+state.prediction.entity.toUpperCase()+' 的预测，重新听到它后可继续验证。':'用下一次目视检验你的判断。';renderInference();renderSignals();toast('已换观察点。脚步惊扰了附近的鸟，给它们一点安静的时间。');}
 function updateUI(){const angle=Math.round((state.yaw+360)%360);const dirs=['N','NE','E','SE','S','SW','W','NW'];const dir=dirs[Math.round(angle/45)%8];$('compass').innerHTML=`─ ─ ─ ─ <b>${dir} ${String(angle).padStart(3,'0')}°</b> ─ ─ ─ ─`;$('clock').textContent=A.formatTime(world.minute);$('day-label').textContent=String(world.day).padStart(3,'0');$('period').textContent=world.minute<300||world.minute>1170?'夜间观测窗口':world.minute<510?'晨间观测窗口':world.minute>960?'暮间观测窗口':'日间观测窗口';$('time').value=Math.floor(world.minute);const e=world.env;$('env-details').textContent=`${e.temp.toFixed(1)}°C / 湿度 ${e.humidity}% / 风 ${e.wind.toFixed(1)} m/s`;$('quiet-bar').style.width=(10+world.disturbance*90)+'%';$('quiet-bar').style.background=world.disturbance>.3?'#e6a476':'#c7dbaa';$('quiet-label').textContent=world.disturbance>.3?'脚步干扰 · 正在恢复':'低干扰 · 适合观察';$('range').textContent=state.zoom?'6.0× / FOV 18°':'1.0× / FOV 110°';$('aim-caption').textContent=state.mode==='eyes'?'聆听 · 转向 · 靠近':state.selected?'信号 '+state.selected.toUpperCase()+(evidence().some(e=>e.key==='visual')?' · 已目视确认':' · 等待细节'):'等待一条线索';$('audio-state').textContent=audio.ctx?audio.muted?'MUTED':isFrozen()?'PAUSED':'LIVE / FFT 1024':'STANDBY';renderSignals();}
 $('start').addEventListener('click',async()=>{try{await audio.start();}catch{toast('音频启动失败，仍可通过声源提示游玩。');}state.started=true;$('sound-gate').hidden=true;renderInference();toast('欢迎来到芦汀湿地。先等一个声音，右侧信号会提示大致方位。');});
 document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>scan(b.dataset.quick));
 $('sample').onclick=()=>scan('audio');$('habitat').onclick=()=>scan('habitat');$('heat').onclick=()=>scan('thermal');$('capture').onclick=()=>scan('visual');$('zoom').onclick=zoom;
 $('mute').onclick=()=>{audio.setMute(!audio.muted);$('mute').textContent=audio.muted?'声音 关':'声音 开';$('mute').setAttribute('aria-pressed',String(audio.muted));};
 $('pause').onclick=()=>{state.paused=!state.paused;$('pause').textContent=state.paused?'继续':'暂停';$('pause').setAttribute('aria-pressed',String(state.paused));syncAudio();};
 $('weather').onchange=e=>{world.weather=e.target.value;toast('天气已改变。观测清晰度、噪声与活动倾向会随之变化。');};
 $('time').oninput=e=>{world.minute=+e.target.value;world.events=[];state.signalSignature='';renderInference();updateUI();};
 $('wait').onclick=()=>{if(!state.started){toast('先开始观测。');return;}for(let i=0;i<100;i++)world.tick(.1);state.lastSequence=world.sequence;state.signalSignature='';updateUI();toast('安静地度过了五分钟。鸟的位置可能已改变，留意新的声音。');};
 $('predict').onclick=()=>{if(!state.selected){toast('先锁定一条信号，再预测下一次目视的栖息地。');return;}if(evidence().some(e=>e.key==='visual')){toast('这个目标已目视确认。请选择新的信号，再提出预测。');return;}state.prediction={entity:state.selected,habitat:$('prediction').value,at:world.minute};$('prediction-status').textContent='预测已锁定：'+A.habitats.find(h=>h.id===state.prediction.habitat).name+'。下一次目视将检验它。';updateMission();toast('预测已锁定。可以等待或换角度，用实际目视检验它。');};
 $('save-record').onclick=()=>{if(!state.pending)return;state.pending.note=$('note').value.trim();state.records.push(state.pending);state.records=state.records.slice(-200);let persisted=true;try{localStorage.setItem(storageKey,JSON.stringify(state.records));}catch{persisted=false;}state.pending=null;$('record-dialog').close();syncAudio();renderJournal();toast(persisted?'已保存到观测档案。这片湿地，多了一个你认识的邻居。':'已保留在本次会话，但本地保存失败，请导出档案。');};
 $('export').onclick=()=>{const blob=new Blob([JSON.stringify({format:'AVIAN-OS v1',simulation:true,exportedAt:new Date().toISOString(),records:state.records},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='AVIAN-OS-观测档案.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('help').onclick=()=>{$('help-dialog').showModal();syncAudio();};$('help-close').onclick=()=>{$('help-dialog').close();syncAudio();};document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',syncAudio));
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));document.querySelectorAll('[data-station]').forEach(b=>b.onclick=()=>changeStation(b.dataset.station));
 $('map').onclick=e=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*1000,y=(e.clientY-r.top)/r.height*800;const nearest=A.stations.map(s=>({s,d:Math.hypot(s.x-x,s.y-y)})).sort((a,b)=>a.d-b.d)[0];if(nearest.d<110)changeStation(nearest.s.id);};
 $('scene').addEventListener('pointerdown',e=>{pointer={id:e.pointerId,x:e.clientX};e.currentTarget.setPointerCapture(e.pointerId);});$('scene').addEventListener('pointermove',e=>{if(pointer&&pointer.id===e.pointerId){state.yaw=A.wrap(state.yaw-(e.clientX-pointer.x)/e.currentTarget.clientWidth*(state.zoom?110/6:110));pointer.x=e.clientX;}});for(const event of ['pointerup','pointercancel'])$('scene').addEventListener(event,()=>pointer=null);
 document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||document.querySelector('dialog[open]')||$('field-view').hidden)return;const k=e.key.toLowerCase();if(['arrowleft','a','arrowright','d',' '].includes(k))e.preventDefault();if(k==='a'||k==='arrowleft')state.yaw=A.wrap(state.yaw-(state.zoom?1:4));if(k==='d'||k==='arrowright')state.yaw=A.wrap(state.yaw+(state.zoom?1:4));if(['1','2','3','4'].includes(k))setMode(['optical','mic','thermal','eyes'][+k-1]);if(k==='z')zoom();if(k===' ')scan('audio');if(k==='p')scan('visual');});
 document.addEventListener('visibilitychange',()=>{last=performance.now();syncAudio();});
 $('guide-list').innerHTML=A.species.map(s=>`<article class="panel bird-card"><div class="eyebrow">${s.night?'DUSK / DAWN':'DAYLIGHT'} · ${s.voice.toUpperCase()}</div><canvas class="guide-bird" data-bird="${s.id}"></canvas><h2>${s.name}</h2><div class="latin">${s.latin}</div><div class="trait">${s.shape}</div><p>${s.habits}</p><small class="tiny">${s.night?'晨昏活动倾向':'白昼活动倾向'} / 合成示意声纹</small></article>`).join('');
 function frame(now){const dt=Math.min((now-last)/1000,.1);last=now;if(!isFrozen()){world.tick(dt);for(const event of world.events.filter(e=>e.id>state.lastSequence).reverse())audio.play(event,world,state.yaw);state.lastSequence=world.sequence;audio.update(world,state.yaw,state.mode);}if(!$('field-view').hidden){renderer.draw(world,state,world.elapsed);renderer.drawMap(world,state);renderer.drawSpectrum(audio,now/1000);}if(now-state.lastUI>250){updateUI();state.lastUI=now;}requestAnimationFrame(frame);}
 // Read-only diagnostics: no species positions or truth are exposed to the UI.
 window.avianDiagnostics=()=>({started:state.started,paused:state.paused,mode:state.mode,zoom:state.zoom,time:A.formatTime(world.minute),day:world.day,yaw:state.yaw,selected:state.selected,evidence:evidence().map(e=>({...e})),probabilities:A.infer(evidence(),currentPrior()).map(c=>({id:c.id,prob:c.prob})),records:state.records.length,audioState:audio.ctx?.state||'uninitialized',audioEvents:audio.emitted,sampleRate:audio.ctx?.sampleRate,fftPeak:audio.bins?Math.max(...audio.bins):0});
 window.avianNavigate=setTab;renderInference();renderJournal();updateUI();setTab(new URLSearchParams(location.search).get('mode')==='explore'?'field':'challenge');requestAnimationFrame(frame);
})();
