(()=>{
'use strict';
const D=AvianChallenges,$=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='avian-os.identification.v2',audio=$('reference-recording');let records=[],credits=[],index=0,current=null,attempt=null,moveUntil=0,stopTimer=null,audioGeneration=0;
try{const data=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(data))records=data.filter(r=>r&&D.cases.some(c=>c.id===r.caseId)&&typeof r.answer==='string'&&Array.isArray(r.evidence)).slice(-200);}catch{}
// Build embeds this metadata for offline use; normal page loads the tiny local JS file.
credits=window.AvianMediaCredits||[];
const clueNames={place:'地点 / 季节 / 时间',habitat:'生境 / 数量',form:'体型 / 颜色 / 局部',behavior:'姿态 / 动作',sound:'声音'};
function stopAudio(){audioGeneration++;audio.pause();audio.currentTime=0;clearTimeout(stopTimer);$('stop-recording').hidden=true;$('recording-strip').classList.remove('playing');$('observe-sound').classList.remove('playing');}
function status(s){$('recording-status').textContent=s;}
function latest(id){return records.findLast(r=>r.caseId===id);}
function pool(){return D.cases.map((c,i)=>({c,i})).filter(({c})=>!!c.advanced===!!current.advanced);}
function renderTabs(){ $('case-tabs').innerHTML=pool().map(({c,i},number)=>`<button class="${i===index?'current ':''}${latest(c.id)?'completed':''}" data-case="${i}" aria-label="案例 ${number+1}：${escape(c.title)}" aria-current="${i===index?'step':'false'}">${String(number+1).padStart(2,'0')}</button>`).join('');document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>load(+b.dataset.case));$('quiz-record-count').textContent=records.length;const track=pool().map(x=>x.c),finished=track.filter(c=>latest(c.id));const right=finished.filter(c=>latest(c.id).correct);$('quiz-progress').textContent=finished.length?`已观察 ${finished.length} / ${track.length} 个案例；${current.advanced?'进阶记录保留候选与把握，不用档案标签充当正确率。':`最近一次判断中 ${right.length} 个符合解析。`}记录只保存在当前浏览器。`:'每次提交会自动保存在这个浏览器里。';}
function notebook(){const texts={place:`${current.area} · ${current.season} · ${current.time}`,habitat:`${current.habitat}。${current.count}。`,form:current.form,behavior:current.behavior,sound:current.voice};$('clue-notebook').innerHTML=Object.entries(clueNames).map(([k,name])=>{const open=attempt.seen.includes(k),selected=attempt.evidence.includes(k);return `<button class="clue-card ${open?'':'locked'} ${selected?'selected':''} ${k==='sound'&&!current.audio?'missing':''}" data-clue="${k}" aria-pressed="${selected}" ${open?'':'disabled'}><small>${name}</small><p>${escape(open?texts[k]:k==='form'?'点击外形观察，记录能看清与看不清的部分。':k==='behavior'?'点击「等它动一动」记录它的行为。':'点击「听声音」检查是否有录音。')}</p></button>`;}).join('');document.querySelectorAll('[data-clue]').forEach(b=>b.onclick=()=>{if(attempt.submitted)return;const k=b.dataset.clue;attempt.evidence=attempt.evidence.includes(k)?attempt.evidence.filter(x=>x!==k):[...attempt.evidence,k];notebook();});}
function buttonState(){const chosen=$('answer-options').querySelector('input:checked');$('submit-guess').disabled=attempt.submitted||!chosen||attempt.seen.length<3;$('submit-help').textContent=attempt.submitted?'判断已保存。仍可查看图像、动作和声音。':attempt.seen.length<3?'先观察至少一项，再选一个答案。':!chosen?'现在可以选择鸟种，或选择暂不定种。':attempt.evidence.length?'已标记支持线索。提交后对照解析。':'可在左侧线索本中点选支持你判断的依据。';}
function load(n){stopAudio();index=(n+D.cases.length)%D.cases.length;current=D.cases[index];attempt={seen:['place','habitat'],evidence:[],submitted:false};moveUntil=0;$('case-title').textContent=current.title;$('case-tag').textContent=current.tag;$('case-number').textContent=`${String(index+1).padStart(2,'0')} / ${D.cases.length}`;$('scene-time').textContent=current.time+' / '+current.season;$('case-opening').textContent=current.opening;$('case-photo').hidden=true;$('case-photo').removeAttribute('src');$('photo-close').hidden=true;$('visual-label').textContent='FIELD SCENE / 情境示意';$('case-scene-caption').textContent=current.open?'根据文字绘制的概括轮廓，不是这只鸟的照片':'先观察整体，再看外形和动作。';$('sound-button-note').textContent=current.audio?'参考实录 / 最长 12 秒':'本次未录到声音';$('answer-reveal').hidden=true;$('guess-reason').value='';$('guess-reason').disabled=false;document.querySelectorAll('[name="confidence"]').forEach(x=>{x.disabled=false;x.checked=x.value==='medium';});document.querySelectorAll('.observe-bar button').forEach(b=>b.classList.remove('seen','playing'));setupTrack();const options=[...current.options];if(!options.includes('暂不定种'))options.push('暂不定种');$('answer-options').innerHTML='<legend class="sr-only">候选鸟种</legend>'+options.map((name,i)=>`<label class="answer-option ${name==='暂不定种'?'uncertain-option':''}"><input type="${current.advanced?'checkbox':'radio'}" name="bird-answer" aria-label="${escape(name)}" value="${escape(name)}"><span>${escape(name)}</span><span class="option-code" aria-hidden="true">${name==='暂不定种'?'?':String.fromCharCode(65+i)}</span></label>`).join('');$('answer-options').onchange=e=>{if(current.advanced){const inputs=[...$('answer-options').querySelectorAll('input')];if(e.target.value==='暂不定种'&&e.target.checked)inputs.filter(x=>x!==e.target).forEach(x=>x.checked=false);else if(e.target.checked)inputs.find(x=>x.value==='暂不定种').checked=false;if(inputs.filter(x=>x.checked).length>3){e.target.checked=false;status('最多保留三个候选；无法缩小范围时可暂不定种。');}}buttonState();};$('case-saved-status').textContent=latest(current.id)?'这个案例已有判断记录；再次提交会新增一次尝试。':'';$('media-attribution').innerHTML=credits.filter(m=>m.case===current.id).map(m=>`<span>${m.type==='bitmap'?'照片':'录音'}：${escape(m.author)} · <a href="${m.licenseUrl||m.source}" target="_blank" rel="noopener noreferrer">${escape(m.license)}</a> · <a href="${m.source}" target="_blank" rel="noopener noreferrer">来源（含鸟名）</a></span>`).join('');status('先观察，再作判断。可反复查看与聆听。');renderTabs();notebook();buttonState();}
function observe(type){if(!attempt.seen.includes(type))attempt.seen.push(type);$('observe-'+(type==='form'?'form':type==='behavior'?'behavior':'sound')).classList.add('seen');notebook();buttonState();}
$('observe-form').onclick=()=>{observe('form');if(current.advanced){showFieldPhoto();status('已展开局部观察。没有被拍清的特征不会自动补全。');return;}if(current.image){$('case-photo').src=current.image;$('case-photo').hidden=false;$('photo-close').hidden=false;$('visual-label').textContent='REFERENCE / 鸟类形态参考';$('case-scene-caption').textContent='参考照片，并非题述现场。观察特征，不会自动显示鸟名。';status('体色、体型与局部特征已加入线索本。');}else{$('case-photo').hidden=true;$('case-scene-caption').textContent='没有照片：保留文字观察，不替观察者补画关键鉴别特征。';status('这道题没有原始照片；已展开完整外形文字。');}};
$('case-photo').onerror=()=>{$('case-photo').hidden=true;$('photo-close').hidden=true;status('参考图加载失败。仍可使用原始文字线索，不把缺图当作证据。');};
$('photo-close').onclick=()=>{$('case-photo').hidden=true;$('photo-close').hidden=true;$('visual-label').textContent='FIELD SCENE / 情境示意';$('case-scene-caption').textContent=current.open?'概括轮廓示意，不代表某个已确认物种':'情境与动作示意，非现场录像。';};
$('observe-behavior').onclick=()=>{observe('behavior');if(current.advanced){status('只有这张原始照片：没有动作序列，不模拟补造行为。');return;}$('photo-close').click();moveUntil=performance.now()+7000;$('case-scene-caption').textContent=current.open?'抬尾与偶尔下地；单一动作并不能锁定物种':'观察动作的节奏，而不是只记一个颜色。';status('动作示意播放约 7 秒；行为描述已加入线索本。');};
$('observe-sound').onclick=async()=>{stopAudio();if(!current.audio){observe('sound');status(current.open?'原始记录没有声音。缺失就是缺失，不据此猜它的叫声。':'这次没有可靠录音。请使用其他已观察到的线索。');return;}const gen=audioGeneration;audio.src=current.audio;audio.volume=.8;status('正在加载参考录音…');try{await audio.play();if(gen!==audioGeneration){audio.pause();return;}observe('sound');$('stop-recording').hidden=false;$('recording-strip').classList.add('playing');$('observe-sound').classList.add('playing');status('正在播放真实参考录音 · 与题述情境不是同一现场');stopTimer=setTimeout(()=>{stopAudio();status('录音片段已结束，可以再次聆听。');},12000);}catch{if(gen===audioGeneration)status('录音未能播放，请重试。声音未听到时，不把它列为判断依据。');}};
audio.onended=()=>{stopAudio();status('录音已结束，可以再听一次。');};audio.onerror=()=>{stopAudio();status('录音加载失败。可重试或根据其他证据保留判断。');};$('stop-recording').onclick=()=>{stopAudio();status('已停止播放。');};
function renderSources(){const media=credits.filter(c=>c.case===current.id);$('case-sources').innerHTML=`<p>${current.advanced?'候选的北京地区背景参考（并非照片地点、拍摄季节或完整候选名录）：':current.open?'题目来自用户提供的朋友观察描述；原记录没有确认物种，候选清单并不穷尽所有可能。':'题目为编写的练习；形态辨认依据：'} <a href="${current.source}" target="_blank" rel="noopener noreferrer">${escape(current.sourceTitle)}</a></p>`+media.map(m=>`<p><b>${m.type==='bitmap'?'照片':'录音'}</b> · ${escape(m.author)} · <a href="${m.licenseUrl||m.source}" target="_blank" rel="noopener noreferrer">${escape(m.license)}</a><br><a href="${m.source}" target="_blank" rel="noopener noreferrer">${escape(m.title.replace('File:',''))}</a><br>${escape(m.change)}${m.type==='audio'||current.advanced?'<br>'+escape(m.description):''}</p>`).join('');}
$('submit-guess').onclick=()=>{if(attempt.submitted)return;const chosen=$('answer-options').querySelector('input:checked');if(!chosen||attempt.seen.length<3)return;if(current.advanced){submitAdvanced();return;}const conf=document.querySelector('[name="confidence"]:checked').value;const r=D.evaluate(current,{answer:chosen.value,confidence:conf,evidence:attempt.evidence});const record={caseId:current.id,title:current.title,...r,evidence:[...attempt.evidence],seen:[...attempt.seen],note:$('guess-reason').value.trim(),createdAt:new Date().toISOString()};records.push(record);records=records.slice(-200);attempt.submitted=true;let saved=true;try{localStorage.setItem(key,JSON.stringify(records));}catch{saved=false;}$('case-saved-status').textContent=saved?'✓ 已保存到「我的判断」':'本地保存失败；记录暂留本页，请导出备份。';$('answer-options').querySelectorAll('input').forEach(x=>x.disabled=true);document.querySelectorAll('[name="confidence"]').forEach(x=>x.disabled=true);$('guess-reason').disabled=true;buttonState();renderTabs();$('result-eyebrow').textContent=current.open?'KEEP THE QUESTION OPEN / 保留候选':'EVIDENCE REVIEW / 对照证据';$('result-title').textContent=current.open?'这次，先不急着给它名字。':r.correct?'你的判断与这些线索吻合。':r.uncertain?'保留不确定，再看一个关键特征。':'换个方向，重新看这些线索。';$('result-stamp').textContent=current.open?'暂不定种':r.correct?'判断吻合':r.uncertain?'继续观察':'重新辨认';$('result-summary').textContent=current.open?`你的选择：${r.answer}。本题没有经过核实的唯一鸟种答案。`:`你的选择：${r.answer} · 本题答案：${current.answer}（${current.latin}）`;$('result-explanation').textContent=current.takeaway;$('next-look').textContent=current.nextLook;const basis=attempt.evidence.length?'你标记了：'+attempt.evidence.map(k=>clueNames[k]).join('、')+'。':'这次没有标记判断依据。下次试着先在“线索本”中选出支持你的观察。';$('reason-feedback').textContent=basis+(r.overconfident?' 这次把握很高，但证据没有支持结论；下次可以先保留候选。':r.correct&&!r.supported?' 答案吻合，再想一想哪条特征最能排除相似鸟。':'');$('comparison-list').innerHTML=current.comparisons.map(([name,why])=>`<div class="comparison-row ${name===current.answer?'correct':''}"><b>${escape(name)}</b><span>${escape(why)}</span></div>`).join('');renderSources();$('answer-reveal').hidden=false;stopAudio();$('answer-reveal').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});};
$('next-case').onclick=()=>{const list=pool().map(x=>x.i);load(list[(list.indexOf(index)+1)%list.length]);$('challenge-view').scrollIntoView({block:'start'});};$('retry-case').onclick=()=>{load(index);$('challenge-view').scrollIntoView({block:'start'});};$('friend-case').onclick=()=>{load(D.cases.findIndex(c=>c.open));};$('export-guesses').onclick=()=>{const blob=new Blob([JSON.stringify({format:'AVIAN-OS identification v3',records},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='AVIAN-OS-我的判断.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('quiz-history-button').onclick=()=>{$('guess-history-list').innerHTML=records.length?[...records].reverse().map(r=>`<article class="guess-history-item"><b>${escape(r.title)}</b><p>${escape(r.answer)} · ${r.advanced?(r.uncertain?'未缩小候选':r.referenceIncluded?'候选包含档案标签':'候选与档案标签不同'):r.correct?'与解析吻合':r.uncertain?'保留不确定':'需复看线索'}</p><small>${escape(r.createdAt.slice(0,10))} · ${r.confidence==='high'?'很确定':r.confidence==='low'?'偏向':'比较确定'}</small>${r.note?'<p>'+escape(r.note)+'</p>':''}</article>`).join(''):'<p>还没有提交过判断。完成一次观察后，这里会留下你的选择与笔记。</p>';stopAudio();$('quiz-history').showModal();};$('quiz-history').querySelector('.close-dialog').onclick=()=>$('quiz-history').close();
document.addEventListener('avian:tab',e=>{if(e.detail!=='challenge'){stopAudio();status('已停止播放。返回后可继续聆听。');}});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopAudio();status('已停止播放。返回后可以重新聆听。');}});
function draw(now){if(!$('challenge-view').hidden&&!document.hidden&&!document.querySelector('dialog[open]')){if(!current.advanced)AvianChallengeArt.draw($('case-scene'),current,now/1000,now<moveUntil&&!matchMedia('(prefers-reduced-motion: reduce)').matches);}requestAnimationFrame(draw);}
function showFieldPhoto(){
 $('case-photo').src=current.image;$('case-photo').hidden=false;$('photo-close').hidden=true;
 $('visual-label').textContent='FIELD PHOTO / 原始信息限制';
 $('case-scene-caption').textContent='真实网络照片 · 保留原有遮挡与角度 · 未人工模糊';
}
function setupTrack(){
 const advanced=!!current.advanced;
 $('track-advanced').setAttribute('aria-pressed',String(advanced));$('track-basic').setAttribute('aria-pressed',String(!advanced));
 $('track-description').textContent=advanced?'六种候选，九张不完整照片。不是北京柳莺的完整名录；无需强行定种，可保留 1–3 个候选，再写下最想补的一条证据。':'入门题提供较完整的形态、情境或参考录音，练习从多条线索辨认鸟种。';
 $('answer-heading').textContent=advanced?'你会保留哪些候选？':'你觉得它是谁？';
 $('answer-intro').textContent=advanced?'可多选，最多 3 个。图片档案标签提交后揭晓；它不等于这张照片足以定种。':'这里没有 AI 排名。根据你看到和听到的，选一个候选。';
 $('guess-reason').placeholder=advanced?'哪些特征看到了？哪些没看清？下一眼最想看哪里？':'例如：长尾摆动让我想到鹡鸰，再用体色排除……';
 $('observe-form').querySelector('strong').textContent=advanced?'读局部特征':'看清外形';
 $('observe-form').querySelector('small').textContent=advanced?'可见 / 遮挡 / 不可确认':'颜色 / 体型 / 局部特征';
 $('observe-behavior').querySelector('strong').textContent=advanced?'检查动作记录':'等它动一动';
 $('observe-behavior').querySelector('small').textContent=advanced?'没有录像，也是一种限制':'姿态 / 活动方式';
 $('photo-limit').hidden=!advanced;$('photo-limit').textContent=advanced?'观察限制 · '+current.tag:'';
 $('case-number').textContent=`${String(pool().findIndex(x=>x.i===index)+1).padStart(2,'0')} / ${pool().length}`;
 $('photo-review').hidden=true;$('photo-review').replaceChildren();$('evidence-audit').replaceChildren();
 $('case-scene').hidden=advanced;
 if(advanced)showFieldPhoto();
}
$('track-advanced').onclick=()=>load(D.cases.findIndex(c=>c.advanced));
$('track-basic').onclick=()=>load(D.cases.findIndex(c=>!c.advanced));
function submitAdvanced(){
 const inputs=[...$('answer-options').querySelectorAll('input:checked')];
 const candidates=inputs.map(x=>x.value).filter(x=>x!=='暂不定种');
 const confidence=document.querySelector('[name="confidence"]:checked').value;
 const r=D.evaluate(current,{candidates,confidence,evidence:attempt.evidence});
 const record={caseId:current.id,title:current.title,...r,evidence:[...attempt.evidence],seen:[...attempt.seen],note:$('guess-reason').value.trim(),createdAt:new Date().toISOString()};
 records.push(record);records=records.slice(-200);attempt.submitted=true;let saved=true;
 try{localStorage.setItem(key,JSON.stringify(records));}catch{saved=false;}
 $('case-saved-status').textContent=saved?'✓ 已保存候选、把握与笔记':'本地保存失败，请导出本页记录备份。';
 $('answer-options').querySelectorAll('input').forEach(x=>x.disabled=true);document.querySelectorAll('[name="confidence"]').forEach(x=>x.disabled=true);$('guess-reason').disabled=true;
 buttonState();renderTabs();stopAudio();
 $('result-eyebrow').textContent='REVIEW THE LIMITS / 复盘证据边界';
 $('result-title').textContent=r.uncertain?'你保留了问题；下一步要补什么？':r.referenceIncluded?'你的候选包含了档案标注的物种。':'你的候选与档案标注不同，复看局部。';
 $('result-stamp').textContent=r.uncertain?'尚未缩小':r.confidenceReview?'复核把握':'保留候选';
 $('result-summary').textContent=`你的判断：${r.answer}。照片档案标注：${current.answer}（${current.latin}）。档案身份由素材来源提供，并非本项目独立复核的鉴定。`;
 $('result-explanation').textContent=current.takeaway;$('next-look').textContent=current.nextLook;
 $('reason-feedback').textContent=(r.uncertain?'不定种避免了误判，但还没有完成缩小候选。试着写下一项能区分近似种的观察。':r.confidenceReview?'这组照片都存在重要信息缺口。“很确定”应能说明如何排除相似种；标签相同也不能代替这个过程。':'保留倾向后，继续检查是否有未列出的候选。')+(r.supported?' 你标记了外形线索，可以逐项检查它是否真正可见。':' 你还没有标记外形依据；下次可以先勾选观察依据。');
 $('evidence-audit').innerHTML=`<div class="audit-item"><small>这张照片留下了什么</small><p>${escape(current.form)}</p></div><div class="audit-item"><small>不能由它推出什么</small><p>没有录音与连续动作记录。看不清的翼斑、腰斑和飞羽长度均不能作为“没有”的证据。</p></div>`;
 $('comparison-list').innerHTML=current.comparisons.map(([name,why])=>`<div class="comparison-row ${name===current.answer?'correct':''}"><b>${escape(name)}${candidates.includes(name)?' · 你保留的候选':''}</b><span>${escape(why)}</span></div>`).join('');
 const examples=['w07','w09','w08','w04','w05','w06'].map(id=>D.cases.find(c=>c.id===id));
 $('photo-review').innerHTML='<h3>换个角度，再认一遍</h3><p>以下为档案标注的六种候选。不是同一只鸟，也不是标准化的颜色或体型对照；每张仍有自己的信息缺口。</p><div class="comparison-photos">'+examples.map(c=>`<figure><img loading="lazy" src="${c.image}" alt="${escape(c.answer)}的另一张参考照片"><figcaption><b>${escape(c.answer)}</b><span>${escape(c.tag)}</span></figcaption></figure>`).join('')+'</div>';
 $('photo-review').hidden=false;renderSources();
 $('case-sources').insertAdjacentHTML('beforeend','<p>六种对照图授权与出处：</p>'+examples.map(c=>{const m=credits.find(x=>x.case===c.id&&x.type==='bitmap');return `<p>${escape(c.answer)} · ${escape(m.author)} · <a href="${m.licenseUrl}" target="_blank" rel="noopener noreferrer">${escape(m.license)}</a> · <a href="${m.source}" target="_blank" rel="noopener noreferrer">原始档案</a></p>`;}).join('')+'<p>鉴别资料：<a href="https://britishbirds.co.uk/sites/default/files/V92_N02_P096_100_A005.pdf" target="_blank" rel="noopener noreferrer">淡眉与黄眉（British Birds）</a> · <a href="https://americanornithology.org/?p=5795" target="_blank" rel="noopener noreferrer">黄腰柳莺鉴别讨论（AOS）</a> · <a href="https://indianbirds.in/pdfs/IB_13_4_FinalHighres.pdf" target="_blank" rel="noopener noreferrer">巨嘴与褐柳莺（Indian BIRDS）</a> · <a href="https://www.dutchbirding.nl/journal/pdf/DB_2001_23_4.pdf" target="_blank" rel="noopener noreferrer">极北柳莺翼形（Dutch Birding）</a>。旧文中的分类与地区情况不直接套用于北京；照片标签仅用于复盘，不以正确率声称完成定种。淡眉照片未核到亚种，不能作为北京当地种群的标准样本。</p>');
 $('answer-reveal').hidden=false;$('answer-reveal').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});
}

load(Math.max(0,D.cases.findIndex(c=>c.id===new URLSearchParams(location.search).get('case'))));requestAnimationFrame(draw);
})();
