(()=>{
'use strict';
const D=AvianChallenges,$=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='avian-os.identification.v2',audio=$('reference-recording');let records=[],credits=[],index=0,current=null,attempt=null,moveUntil=0,stopTimer=null,audioGeneration=0;
try{const data=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(data))records=data.filter(r=>r&&D.cases.some(c=>c.id===r.caseId)&&typeof r.answer==='string'&&Array.isArray(r.evidence)).slice(-200);}catch{}
// Build embeds this metadata for offline use; normal page loads the tiny local JS file.
credits=window.AvianMediaCredits||[];
const clueNames={place:'地点 / 季节 / 时间',habitat:'生境 / 数量',form:'体型 / 颜色 / 局部',behavior:'姿态 / 动作',sound:'声音'};
function stopAudio(){audioGeneration++;audio.pause();audio.currentTime=0;clearTimeout(stopTimer);$('stop-recording').hidden=true;$('recording-strip').classList.remove('playing');$('observe-sound').classList.remove('playing');}
function status(s){$('recording-status').textContent=s;}
function latest(id){return records.findLast(r=>r.caseId===id);}
function renderTabs(){ $('case-tabs').innerHTML=D.cases.map((c,i)=>`<button class="${i===index?'current ':''}${latest(c.id)?'completed':''}" data-case="${i}" aria-label="案例 ${i+1}：${escape(c.title)}" aria-current="${i===index?'step':'false'}">${String(i+1).padStart(2,'0')}</button>`).join('');document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>load(+b.dataset.case));$('quiz-record-count').textContent=records.length;const finished=D.cases.filter(c=>latest(c.id));const right=finished.filter(c=>latest(c.id).correct);$('quiz-progress').textContent=finished.length?`已观察 ${finished.length} / ${D.cases.length} 个案例；最近一次判断中 ${right.length} 个符合解析。记录只保存在当前浏览器。`:'每次提交会自动保存在这个浏览器里。';}
function notebook(){const texts={place:`${current.area} · ${current.season} · ${current.time}`,habitat:`${current.habitat}。${current.count}。`,form:current.form,behavior:current.behavior,sound:current.voice};$('clue-notebook').innerHTML=Object.entries(clueNames).map(([k,name])=>{const open=attempt.seen.includes(k),selected=attempt.evidence.includes(k);return `<button class="clue-card ${open?'':'locked'} ${selected?'selected':''} ${k==='sound'&&!current.audio?'missing':''}" data-clue="${k}" aria-pressed="${selected}" ${open?'':'disabled'}><small>${name}</small><p>${escape(open?texts[k]:k==='form'?'点击「看清外形」留下这条观察。':k==='behavior'?'点击「等它动一动」记录它的行为。':'点击「听声音」检查是否有录音。')}</p></button>`;}).join('');document.querySelectorAll('[data-clue]').forEach(b=>b.onclick=()=>{if(attempt.submitted)return;const k=b.dataset.clue;attempt.evidence=attempt.evidence.includes(k)?attempt.evidence.filter(x=>x!==k):[...attempt.evidence,k];notebook();});}
function buttonState(){const chosen=$('answer-options').querySelector('input:checked');$('submit-guess').disabled=attempt.submitted||!chosen||attempt.seen.length<3;$('submit-help').textContent=attempt.submitted?'判断已保存。仍可查看图像、动作和声音。':attempt.seen.length<3?'先观察至少一项，再选一个答案。':!chosen?'现在可以选择鸟种，或选择暂不定种。':attempt.evidence.length?'已标记支持线索。提交后对照解析。':'可在左侧线索本中点选支持你判断的依据。';}
function load(n){stopAudio();index=(n+D.cases.length)%D.cases.length;current=D.cases[index];attempt={seen:['place','habitat'],evidence:[],submitted:false};moveUntil=0;$('case-title').textContent=current.title;$('case-tag').textContent=current.tag;$('case-number').textContent=`${String(index+1).padStart(2,'0')} / ${D.cases.length}`;$('scene-time').textContent=current.time+' / '+current.season;$('case-opening').textContent=current.opening;$('case-photo').hidden=true;$('case-photo').removeAttribute('src');$('photo-close').hidden=true;$('visual-label').textContent='FIELD SCENE / 情境示意';$('case-scene-caption').textContent=current.open?'根据文字绘制的概括轮廓，不是这只鸟的照片':'先观察整体，再看外形和动作。';$('sound-button-note').textContent=current.audio?'参考实录 / 最长 12 秒':'本次未录到声音';$('answer-reveal').hidden=true;$('guess-reason').value='';$('guess-reason').disabled=false;document.querySelectorAll('[name="confidence"]').forEach(x=>{x.disabled=false;x.checked=x.value==='medium';});document.querySelectorAll('.observe-bar button').forEach(b=>b.classList.remove('seen','playing'));const options=[...current.options];if(!options.includes('暂不定种'))options.push('暂不定种');$('answer-options').innerHTML='<legend class="sr-only">候选鸟种</legend>'+options.map((name,i)=>`<label class="answer-option ${name==='暂不定种'?'uncertain-option':''}"><input type="radio" name="bird-answer" aria-label="${escape(name)}" value="${escape(name)}"><span>${escape(name)}</span><span class="option-code" aria-hidden="true">${name==='暂不定种'?'?':String.fromCharCode(65+i)}</span></label>`).join('');$('answer-options').onchange=buttonState;$('case-saved-status').textContent=latest(current.id)?'这个案例已有判断记录；再次提交会新增一次尝试。':'';$('media-attribution').innerHTML=credits.filter(m=>m.case===current.id).map(m=>`<span>${m.type==='bitmap'?'照片':'录音'}：${escape(m.author)} · <a href="${m.licenseUrl||m.source}" target="_blank" rel="noopener noreferrer">${escape(m.license)}</a> · <a href="${m.source}" target="_blank" rel="noopener noreferrer">来源（含鸟名）</a></span>`).join('');status('先观察，再作判断。可反复查看与聆听。');renderTabs();notebook();buttonState();}
function observe(type){if(!attempt.seen.includes(type))attempt.seen.push(type);$('observe-'+(type==='form'?'form':type==='behavior'?'behavior':'sound')).classList.add('seen');notebook();buttonState();}
$('observe-form').onclick=()=>{observe('form');if(current.image){$('case-photo').src=current.image;$('case-photo').hidden=false;$('photo-close').hidden=false;$('visual-label').textContent='REFERENCE / 鸟类形态参考';$('case-scene-caption').textContent='参考照片，并非题述现场。观察特征，不会自动显示鸟名。';status('体色、体型与局部特征已加入线索本。');}else{$('case-photo').hidden=true;$('case-scene-caption').textContent='没有照片：保留文字观察，不替观察者补画关键鉴别特征。';status('这道题没有原始照片；已展开完整外形文字。');}};
$('case-photo').onerror=()=>{$('case-photo').hidden=true;$('photo-close').hidden=true;status('参考图加载失败。仍可使用原始文字线索，不把缺图当作证据。');};
$('photo-close').onclick=()=>{$('case-photo').hidden=true;$('photo-close').hidden=true;$('visual-label').textContent='FIELD SCENE / 情境示意';$('case-scene-caption').textContent=current.open?'概括轮廓示意，不代表某个已确认物种':'情境与动作示意，非现场录像。';};
$('observe-behavior').onclick=()=>{observe('behavior');$('photo-close').click();moveUntil=performance.now()+7000;$('case-scene-caption').textContent=current.open?'抬尾与偶尔下地；单一动作并不能锁定物种':'观察动作的节奏，而不是只记一个颜色。';status('动作示意播放约 7 秒；行为描述已加入线索本。');};
$('observe-sound').onclick=async()=>{stopAudio();if(!current.audio){observe('sound');status(current.open?'原始记录没有声音。缺失就是缺失，不据此猜它的叫声。':'这次没有可靠录音。请使用其他已观察到的线索。');return;}const gen=audioGeneration;audio.src=current.audio;audio.volume=.8;status('正在加载参考录音…');try{await audio.play();if(gen!==audioGeneration){audio.pause();return;}observe('sound');$('stop-recording').hidden=false;$('recording-strip').classList.add('playing');$('observe-sound').classList.add('playing');status('正在播放真实参考录音 · 与题述情境不是同一现场');stopTimer=setTimeout(()=>{stopAudio();status('录音片段已结束，可以再次聆听。');},12000);}catch{if(gen===audioGeneration)status('录音未能播放，请重试。声音未听到时，不把它列为判断依据。');}};
audio.onended=()=>{stopAudio();status('录音已结束，可以再听一次。');};audio.onerror=()=>{stopAudio();status('录音加载失败。可重试或根据其他证据保留判断。');};$('stop-recording').onclick=()=>{stopAudio();status('已停止播放。');};
function renderSources(){const media=credits.filter(c=>c.case===current.id);$('case-sources').innerHTML=`<p>${current.open?'题目来自用户提供的朋友观察描述；原记录没有确认物种，候选清单并不穷尽所有可能。':'题目为编写的练习；形态辨认依据：'} <a href="${current.source}" target="_blank" rel="noopener noreferrer">${escape(current.sourceTitle)}</a></p>`+media.map(m=>`<p><b>${m.type==='bitmap'?'照片':'录音'}</b> · ${escape(m.author)} · <a href="${m.licenseUrl||m.source}" target="_blank" rel="noopener noreferrer">${escape(m.license)}</a><br><a href="${m.source}" target="_blank" rel="noopener noreferrer">${escape(m.title.replace('File:',''))}</a><br>${escape(m.change)}${m.type==='audio'?'<br>'+escape(m.description):''}</p>`).join('');}
$('submit-guess').onclick=()=>{if(attempt.submitted)return;const chosen=$('answer-options').querySelector('input:checked');if(!chosen||attempt.seen.length<3)return;const conf=document.querySelector('[name="confidence"]:checked').value;const r=D.evaluate(current,{answer:chosen.value,confidence:conf,evidence:attempt.evidence});const record={caseId:current.id,title:current.title,...r,evidence:[...attempt.evidence],seen:[...attempt.seen],note:$('guess-reason').value.trim(),createdAt:new Date().toISOString()};records.push(record);records=records.slice(-200);attempt.submitted=true;let saved=true;try{localStorage.setItem(key,JSON.stringify(records));}catch{saved=false;}$('case-saved-status').textContent=saved?'✓ 已保存到「我的判断」':'本地保存失败；记录暂留本页，请导出备份。';$('answer-options').querySelectorAll('input').forEach(x=>x.disabled=true);document.querySelectorAll('[name="confidence"]').forEach(x=>x.disabled=true);$('guess-reason').disabled=true;buttonState();renderTabs();$('result-eyebrow').textContent=current.open?'KEEP THE QUESTION OPEN / 保留候选':'EVIDENCE REVIEW / 对照证据';$('result-title').textContent=current.open?'这次，先不急着给它名字。':r.correct?'你的判断与这些线索吻合。':r.uncertain?'保留不确定，再看一个关键特征。':'换个方向，重新看这些线索。';$('result-stamp').textContent=current.open?'暂不定种':r.correct?'判断吻合':r.uncertain?'继续观察':'重新辨认';$('result-summary').textContent=current.open?`你的选择：${r.answer}。本题没有经过核实的唯一鸟种答案。`:`你的选择：${r.answer} · 本题答案：${current.answer}（${current.latin}）`;$('result-explanation').textContent=current.takeaway;$('next-look').textContent=current.nextLook;const basis=attempt.evidence.length?'你标记了：'+attempt.evidence.map(k=>clueNames[k]).join('、')+'。':'这次没有标记判断依据。下次试着先在“线索本”中选出支持你的观察。';$('reason-feedback').textContent=basis+(r.overconfident?' 这次把握很高，但证据没有支持结论；下次可以先保留候选。':r.correct&&!r.supported?' 答案吻合，再想一想哪条特征最能排除相似鸟。':'');$('comparison-list').innerHTML=current.comparisons.map(([name,why])=>`<div class="comparison-row ${name===current.answer?'correct':''}"><b>${escape(name)}</b><span>${escape(why)}</span></div>`).join('');renderSources();$('answer-reveal').hidden=false;stopAudio();$('answer-reveal').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});};
$('next-case').onclick=()=>{load(index+1);$('challenge-view').scrollIntoView({block:'start'});};$('retry-case').onclick=()=>{load(index);$('challenge-view').scrollIntoView({block:'start'});};$('friend-case').onclick=()=>{load(D.cases.findIndex(c=>c.open));};$('export-guesses').onclick=()=>{const blob=new Blob([JSON.stringify({format:'AVIAN-OS identification v2',records},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='AVIAN-OS-我的判断.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('quiz-history-button').onclick=()=>{$('guess-history-list').innerHTML=records.length?[...records].reverse().map(r=>`<article class="guess-history-item"><b>${escape(r.title)}</b><p>${escape(r.answer)} · ${r.correct?'与解析吻合':r.uncertain?'保留不确定':'需复看线索'}</p><small>${escape(r.createdAt.slice(0,10))} · ${r.confidence==='high'?'很确定':r.confidence==='low'?'偏向':'比较确定'}</small>${r.note?'<p>'+escape(r.note)+'</p>':''}</article>`).join(''):'<p>还没有提交过判断。完成一次观察后，这里会留下你的选择与笔记。</p>';stopAudio();$('quiz-history').showModal();};$('quiz-history').querySelector('.close-dialog').onclick=()=>$('quiz-history').close();
document.addEventListener('avian:tab',e=>{if(e.detail!=='challenge'){stopAudio();status('已停止播放。返回后可继续聆听。');}});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopAudio();status('已停止播放。返回后可以重新聆听。');}});
function draw(now){if(!$('challenge-view').hidden&&!document.hidden&&!document.querySelector('dialog[open]'))AvianChallengeArt.draw($('case-scene'),current,now/1000,now<moveUntil&&!matchMedia('(prefers-reduced-motion: reduce)').matches);requestAnimationFrame(draw);}
load(Math.max(0,D.cases.findIndex(c=>c.id===new URLSearchParams(location.search).get('case'))));requestAnimationFrame(draw);
})();
