(function(root){
'use strict';
const cases=[
{id:'02',title:'水边那个不停摆尾的身影',tag:'入门 · 组合特征',area:'北京 · 城市河岸',season:'4 月上旬',time:'08:20',weather:'晴，微风',count:'2 只，间隔数米',habitat:'开阔浅水边，石滩与步道交界',opening:'河边，两只小鸟在石头和步道之间走动。先看它的轮廓，再留意它怎么动。',form:'身体修长，尾很长。黑、白、灰三色分明，翅上有白色；没有明显黄色腹部。',behavior:'在地面小步行走、停下啄食；长尾反复上下摆动。',voice:'参考录音中可听到短促、较尖的鸣声。声音只作补充，不能单凭一个“啾”字定种。',answer:'白鹡鸰',latin:'Motacilla alba',options:['灰鹡鸰','树麻雀','白鹡鸰','黄鹡鸰'],key:['form','behavior'],image:'assets/reference/02-image.jpg',audio:'assets/reference/02-audio.mp3',art:'wagtail',takeaway:'长尾摆动把范围缩到鹡鸰类；黑白灰配色与缺少黄色腹部，再支持白鹡鸰。',comparisons:[['白鹡鸰','长尾、黑白灰体色与地面行走的组合吻合。'],['灰鹡鸰','同样常在水边摆尾；本题没有观察到它的重要黄色下体特征。'],['黄鹡鸰','通常需要考虑黄色下体；与本题的黑白灰组合不符。'],['树麻雀','体态较敦实、嘴较粗短，也没有如此长的尾。']],source:'https://ebird.org/species/whiwag',sourceTitle:'Cornell Lab · White Wagtail',nextLook:'继续看头部花纹；本题只判断到物种，不进一步猜亚种。'},
{id:'03',title:'矮墙上，一个橙色的停顿',tag:'入门 · 看对位置',area:'北京 · 公园林缘',season:'11 月上旬',time:'15:10',weather:'晴，稍凉',count:'1 只，单独活动',habitat:'灌丛外侧的矮墙与低枝',opening:'一只小鸟从矮墙落到地面，又返回低枝。它的颜色很醒目，但要看清白色究竟长在哪里。',form:'灰色头顶和后颈、黑色脸，胸腹橙色；暗色翅膀上有一块明显白斑。',behavior:'在低处停栖，间歇落地取食；尾部颤动，橙色尾侧时隐时现。',voice:'这次没有留下声音记录。安静不代表它属于某一种鸟。',answer:'北红尾鸲',latin:'Phoenicurus auroreus',options:['红胁蓝尾鸲','北红尾鸲','鹊鸲','白鹡鸰'],key:['form','behavior'],image:'assets/reference/03-image.jpg',audio:null,art:'redstart',takeaway:'先定位白斑：它在翅上。灰顶、黑脸、橙色胸腹与白色翼斑共同支持雄性北红尾鸲。',comparisons:[['北红尾鸲','本题描述的雄鸟颜色组合与白色翼斑吻合。'],['红胁蓝尾鸲','不能因为有橙色就下结论；它的蓝尾与两胁颜色分布需要另外确认。'],['鹊鸲','黑白配色明显，但没有本题的橙色胸腹与灰色头顶组合。'],['白鹡鸰','长尾可以造成联想，但橙色胸腹与停栖外形不符。']],source:'https://ebird.org/species/daured1',sourceTitle:'Cornell Lab · Daurian Redstart',nextLook:'如果只见到灰褐色雌鸟，仍要确认翼上白斑与尾侧颜色，不能照搬雄鸟配色。'},
{id:'04',title:'草籽旁的小队伍',tag:'入门 · 数量不是答案',area:'北京 · 社区绿地',season:'10 月中旬',time:'09:35',weather:'多云',count:'约 8 只，松散成群',habitat:'草坪边、低矮篱笆与灌丛',opening:'一小群鸟在草地上啄食，受扰时一起上了篱笆。“成群”是线索，却不是物种名称。',form:'栗褐色头顶、白色脸颊，脸颊中央有黑斑；喉部黑色，嘴粗短。',behavior:'在地面跳跃和啄食，几只互相靠近，又一起转移到篱笆。',voice:'可以听到短促、反复的啁啾声。结合头部特征判断，不把所有啁啾声都归为麻雀。',answer:'树麻雀',latin:'Passer montanus',options:['白头鹎','大山雀','家麻雀','树麻雀'],key:['form'],image:'assets/reference/04-image.jpg',audio:'assets/reference/04-audio.mp3',art:'sparrow',takeaway:'成群和粗短嘴只是缩小范围；栗色顶冠与白脸上的黑色颊斑是本题更有区分力的组合。',comparisons:[['树麻雀','栗顶、白颊黑斑和粗短嘴吻合。'],['家麻雀','不能只说“像麻雀”；本题的黑色颊斑与栗色顶冠组合更支持树麻雀。'],['大山雀','头脸也有黑白，但应进一步比较顶冠、喉胸花纹与嘴形。'],['白头鹎','体型和嘴形不同，也不具有本题的栗顶黑颊斑组合。']],source:'https://ebird.org/species/eutspa',sourceTitle:'Cornell Lab · Eurasian Tree Sparrow',nextLook:'试着只观察一只的脸，而不是被整个鸟群的动作带走注意力。'},
{id:'05',title:'水面掠过的一抹蓝',tag:'进阶 · 形态与行为',area:'杭州 · 湿地池塘',season:'7 月中旬',time:'07:10',weather:'晴，水面平静',count:'1 只',habitat:'水面上方的低矮枯枝',opening:'先是一道低飞的蓝色闪光。几秒后，小鸟停在伸向水面的枯枝上，长时间盯着下方。',form:'体型小而紧凑，蓝绿色背部、橙色下体，嘴长而直；喉部浅色。',behavior:'从低枝向水面俯冲，随后回到枝头；也会沿水面快速低飞。',voice:'参考录音中有较尖细的短鸣。录音环境与题目情境不同，重点比较声音质感。',answer:'普通翠鸟',latin:'Alcedo atthis',options:['蓝翡翠','白胸翡翠','普通翠鸟','白鹡鸰'],key:['form','behavior'],image:'assets/reference/05-image.jpg',audio:'assets/reference/05-audio.mp3',art:'kingfisher',takeaway:'水边俯冲支持翠鸟类，蓝绿背与橙色下体、小而紧凑的体型和长直嘴进一步支持普通翠鸟。',comparisons:[['普通翠鸟','蓝绿背、橙腹、小体型与临水停栖的组合吻合。'],['白胸翡翠','不能只凭蓝色翅背判断；还应见到它明显的白胸与不同的头体配色。'],['蓝翡翠','需要比较嘴色、头部和下体；本题的橙色下体与形态组合更支持普通翠鸟。'],['白鹡鸰','水边活动相同，但嘴形、体色和俯冲取食方式不同。']],source:'https://ebird.org/species/comkin1',sourceTitle:'Cornell Lab · Common Kingfisher',nextLook:'观察嘴的上下颜色可以带来更多信息，但本题不要求判断性别。'},
{id:'06',title:'树冠边缘的白色后脑勺',tag:'进阶 · 避免望文生义',area:'杭州 · 城市公园',season:'4 月中旬',time:'06:50',weather:'薄云',count:'3 只，附近另有动静',habitat:'林缘灌木与小乔木，中层枝叶',opening:'几只鸟在枝叶间短距离移动。光线落到其中一只的头后部，露出一片白色。',form:'头部黑白相间，枕部有白色；背部偏橄榄灰，下体浅色，嘴较细。',behavior:'在灌丛和小乔木间跳跃、停栖，几只鸟短距离结伴移动。',voice:'这次没有可靠录音。请结合枕部白色的位置与整体体态，而不是补想一个声音。',answer:'白头鹎',latin:'Pycnonotus sinensis',options:['白头鹎','乌鸫','树麻雀','大山雀'],key:['form','habitat'],image:'assets/reference/06-image.jpg',audio:null,art:'bulbul',takeaway:'“白头”不意味着整颗头都是白色。黑白头纹、白色枕部与橄榄灰背的组合更关键。',comparisons:[['白头鹎','头后白色、黑白头纹与橄榄灰背吻合。'],['大山雀','也有黑白头纹，但要分清白色位于脸颊还是枕部，并比较胸腹。'],['树麻雀','应有栗褐顶冠、黑色颊斑与粗短嘴，不是这里的头纹组合。'],['乌鸫','体态和尾更大，成鸟通常不呈现本题这种黑白头纹。']],source:'https://ebird.org/species/livbul1',sourceTitle:'Cornell Lab · Light-vented Bulbul',nextLook:'白头鹎不同地区的头纹存在差异，本题只要求识别这张参考图与文字中的组合。'},
{id:'01',title:'朋友的那道题：林下灰褐小鸟',tag:'开放题 · 保留不确定',area:'北京近郊 · 湿地公园',season:'9 月下旬',time:'15:00',weather:'未记录',count:'1 只，单独活动',habitat:'树林靠近水面一侧，树木中下层',opening:'九月下旬某日下午三点，在北京近郊湿地公园看到一只小鸟：在临水的林子中下层单独活动，偶尔落地。下面只有当时留下的观察，没有照片，也没有录音。',form:'整体灰褐色，体型在麻雀和白头鹎之间，眼大；观察者写下“尾下覆羽有白斑”。未记录尾羽本身、腰部和翼斑的颜色。',behavior:'在枝上频繁抬尾，偶尔下地。观察者没有记录持续时长或完整动作序列。',voice:'没有录音，也没有可靠鸣声描述。这条证据缺失，不能自动补齐。',answer:'暂不定种',latin:'Evidence incomplete',options:['北红尾鸲（雌）','红胁蓝尾鸲（雌／一龄）','红喉歌鸲（雌）','暂不定种'],key:['form','behavior'],image:null,audio:null,art:'unknown',open:true,takeaway:'这里没有一条经过核实的定种答案。灰褐色、林下活动和抬尾可以支持多种候选；“尾下覆羽白斑”还需要确认观察部位。保留候选并补证，比硬猜一个名字更符合观鸟。',comparisons:[['北红尾鸲（雌）','是待排查候选之一；还需要看翼上白斑、尾侧及腰部颜色。'],['红胁蓝尾鸲（雌／一龄）','需要进一步确认尾羽、两胁与头脸特征。现有描述不能充分支持或排除。'],['红喉歌鸲（雌）','同样需要观察头脸、胸部与尾部；林下活动不能单独支持它。'],['暂不定种','本题推荐：关键特征缺失，保留原始观察，并记录下一步要看什么。']],source:'https://ebird.org/species/daured1',sourceTitle:'北红尾鸲候选特征参考 · Cornell Lab',nextLook:'拍到完整尾羽、腰与翼；核实白斑位置；补充头脸和胸部花纹，并尽可能留下录音。'}
];
function evaluate(c,input){const unsure=input.answer==='暂不定种';const correct=input.answer===c.answer;const relevant=(input.evidence||[]).filter(k=>c.key.includes(k));return {correct,uncertain:unsure&&!c.open,calibrated:correct||unsure,overconfident:!correct&&!unsure&&input.confidence==='high',supported:relevant.length>0,relevant,answer:input.answer,confidence:input.confidence||'medium'};}
const api={cases,evaluate,version:2};if(typeof module!=='undefined')module.exports=api;else root.AvianChallenges=api;
})(globalThis);
