window.AvianMediaCredits = [
  {
    "case": "02",
    "type": "bitmap",
    "file": "assets/reference/02-image.jpg",
    "title": "File:Bachstelze - Bergeronnette grise - White wagtail - Motacilla alba - 03.jpg",
    "author": "NorbertNagel",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bachstelze_-_Bergeronnette_grise_-_White_wagtail_-_Motacilla_alba_-_03.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/22/Bachstelze_-_Bergeronnette_grise_-_White_wagtail_-_Motacilla_alba_-_03.jpg/1280px-Bachstelze_-_Bergeronnette_grise_-_White_wagtail_-_Motacilla_alba_-_03.jpg",
    "description": "White Wagtail (Motacilla alba alba) with nesting material in its beak in the Mönchbruch nature reserve, Germany, in early April.",
    "change": "Wikimedia 1200px thumbnail; displayed with responsive crop"
  },
  {
    "case": "02",
    "type": "audio",
    "file": "assets/reference/02-audio.mp3",
    "title": "File:Motacilla alba - White Wagtail XC501786.mp3",
    "author": "Hannu Varkki",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Motacilla_alba_-_White_Wagtail_XC501786.mp3",
    "download": "https://upload.wikimedia.org/wikipedia/commons/4/42/Motacilla_alba_-_White_Wagtail_XC501786.mp3",
    "description": ":bird-seen:yes\nplayback-used:no\nCommon name: White Wagtail\nType: call\nGenus: Motacilla\nSpecies: alba\nLocation: Puotila, Helsinki, Uusimaa\nCountry: Finland\nElevation: 10 m",
    "change": "Unmodified reference recording; playback stops after 12 seconds"
  },
  {
    "case": "03",
    "type": "bitmap",
    "file": "assets/reference/03-image.jpg",
    "title": "File:Phoenicurus auroreus (male).JPG",
    "author": "Alpsdake",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Phoenicurus_auroreus_(male).JPG",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/Phoenicurus_auroreus_%28male%29.JPG/1280px-Phoenicurus_auroreus_%28male%29.JPG",
    "description": "Daurian Redstart (Phoenicurus auroreus), male in Aichi prefecture, Japan.",
    "change": "Wikimedia 1200px thumbnail; displayed with responsive crop"
  },
  {
    "case": "04",
    "type": "bitmap",
    "file": "assets/reference/04-image.jpg",
    "title": "File:Tree Sparrow August 2007 Osaka Japan.jpg",
    "author": "Laitche",
    "license": "Public domain",
    "licenseUrl": "",
    "source": "https://commons.wikimedia.org/wiki/File:Tree_Sparrow_August_2007_Osaka_Japan.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/98/Tree_Sparrow_August_2007_Osaka_Japan.jpg/1280px-Tree_Sparrow_August_2007_Osaka_Japan.jpg",
    "description": "Tree sparrow in Nagai Park, Osaka, Japan",
    "change": "Wikimedia 1200px thumbnail; displayed with responsive crop"
  },
  {
    "case": "04",
    "type": "audio",
    "file": "assets/reference/04-audio.mp3",
    "title": "File:Passer montanus - Eurasian Tree Sparrow XC347807.mp3",
    "author": "Derek Paulo",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Passer_montanus_-_Eurasian_Tree_Sparrow_XC347807.mp3",
    "download": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Passer_montanus_-_Eurasian_Tree_Sparrow_XC347807.mp3",
    "description": ":bird-seen:yes\nplayback-used:no\nCommon name: Eurasian Tree Sparrow\nType: call, song\nGenus: Passer\nSpecies: montanus\nLocation: CPAC, Murcia, Negros Occidental, Western Visayas\nCountry: Philippines\nElevation: 220 m",
    "change": "Unmodified reference recording; playback stops after 12 seconds"
  },
  {
    "case": "05",
    "type": "bitmap",
    "file": "assets/reference/05-image.jpg",
    "title": "File:Common Kingfisher Alcedo atthis.jpg",
    "author": "Andreas Trepte",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Common_Kingfisher_Alcedo_atthis.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cc/Common_Kingfisher_Alcedo_atthis.jpg/1280px-Common_Kingfisher_Alcedo_atthis.jpg",
    "description": "Common Kingfisher, Marburg, Germany",
    "change": "Wikimedia 1200px thumbnail; displayed with responsive crop"
  },
  {
    "case": "05",
    "type": "audio",
    "file": "assets/reference/05-audio.mp3",
    "title": "File:Alcedo atthis - Common Kingfisher XC476785.mp3",
    "author": "Marie-Lan Taÿ Pamart",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Alcedo_atthis_-_Common_Kingfisher_XC476785.mp3",
    "download": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Alcedo_atthis_-_Common_Kingfisher_XC476785.mp3",
    "description": ":Kingfisher calling in flight whilst crossing a lake (and passing the recorder), a former gravel pit reconverted as a nature reserve.\nBackground noises: unidentified immature Larus sp. (magna), commercial plane\nDistance: ~30m at closest\nEquipment: Tascam DR-100mkIII + Sennheiser ME-66/K6 + Rycote Windjammer\nEdits: -12dB high-pass filter at 4500Hz\nbird-seen:yes\nplayback-used:no\nCommon name: Common Kingfisher\nType: flight call\nGenus: Alcedo\nSpecies: atthis\nLocation: Trilbardou, Seine-et-Marne, Île-de-France\nCountry: France\nElevation: 40 m",
    "change": "Unmodified reference recording; playback stops after 12 seconds"
  },
  {
    "case": "06",
    "type": "bitmap",
    "file": "assets/reference/06-image.jpg",
    "title": "File:Light-vented Bulbul (Pycnonotus sinensis).jpg",
    "author": "Herbertkikoy",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Light-vented_Bulbul_(Pycnonotus_sinensis).jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/Light-vented_Bulbul_%28Pycnonotus_sinensis%29.jpg/1280px-Light-vented_Bulbul_%28Pycnonotus_sinensis%29.jpg",
    "description": "The Light-vented Bulbul (Pycnonotus sinensis) is an adaptable songbird commonly found in woodlands, parks, farmland, and urban gardens across East Asia. It feeds on fruits, nectar, insects, and small invertebrates, making it an important seed disperser and a natural helper in controlling insect populations. Its cheerful calls and active behavior make it easy to notice even in busy cities. This species thrives where trees and shrubs provide plenty of food and shelter.",
    "change": "Wikimedia 1200px thumbnail; displayed with responsive crop"
  },
  {
    "case": "w01",
    "type": "bitmap",
    "file": "assets/reference/w01.jpg",
    "title": "File:Yellow-browed Warbler by Tisha Mukherjee 05.jpg",
    "author": "Tisha Mukherjee",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Yellow-browed_Warbler_by_Tisha_Mukherjee_05.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3c/Yellow-browed_Warbler_by_Tisha_Mukherjee_05.jpg/1280px-Yellow-browed_Warbler_by_Tisha_Mukherjee_05.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "description": "Yellow-browed Warbler (Phylloscopus inornatus, Phylloscopidae, Passeriformes) in Rabindra Sarobar, West Bengal, India.",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w02",
    "type": "bitmap",
    "file": "assets/reference/w02.jpg",
    "title": "File:Hume's Warbler (Phylloscopus humei) - 48828586077.jpg",
    "author": "gilgit2",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hume%27s_Warbler_(Phylloscopus_humei)_-_48828586077.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/Hume%27s_Warbler_%28Phylloscopus_humei%29_-_48828586077.jpg/1280px-Hume%27s_Warbler_%28Phylloscopus_humei%29_-_48828586077.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "description": "Hume's Warbler (Phylloscopus humei) captured at Borit, Gojal, Gilgit-Baltistan, Pakistan with Canon EOS 7D Mark II",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w03",
    "type": "bitmap",
    "file": "assets/reference/w03.jpg",
    "title": "File:Pallas's leaf warbler (Phylloscopus proregulus) 2022.jpg",
    "author": "TRinaud",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pallas%27s_leaf_warbler_(Phylloscopus_proregulus)_2022.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/67/Pallas%27s_leaf_warbler_%28Phylloscopus_proregulus%29_2022.jpg/1280px-Pallas%27s_leaf_warbler_%28Phylloscopus_proregulus%29_2022.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "description": "Helgoland, Schleswig-Holstein, Germany",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w04",
    "type": "bitmap",
    "file": "assets/reference/w04.jpg",
    "title": "File:Dusky Warbler in Baruipur November 2025 by Tisha Mukherjee 03.jpg",
    "author": "Tisha Mukherjee",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Dusky_Warbler_in_Baruipur_November_2025_by_Tisha_Mukherjee_03.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Dusky_Warbler_in_Baruipur_November_2025_by_Tisha_Mukherjee_03.jpg/1280px-Dusky_Warbler_in_Baruipur_November_2025_by_Tisha_Mukherjee_03.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "description": "Dusky Warbler (Phylloscopus fuscatus, Phylloscopidae, Passeriformes) in Baruipur, West Bengal, India.",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w05",
    "type": "bitmap",
    "file": "assets/reference/w05.jpg",
    "title": "File:Radde's Warbler - Thailand S4E1407 (18645038584) (2).jpg",
    "author": "Francesco Veronesi from Italy",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Radde%27s_Warbler_-_Thailand_S4E1407_(18645038584)_(2).jpg",
    "download": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Radde%27s_Warbler_-_Thailand_S4E1407_%2818645038584%29_%282%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
    "description": "Radde's Warbler - Thailand_S4E1407",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w06",
    "type": "bitmap",
    "file": "assets/reference/w06.jpg",
    "title": "File:Arctic Warbler (Phylloscopus borealis), Skaw - geograph.org.uk - 3812845.jpg",
    "author": "Mike Pennington ",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Arctic_Warbler_(Phylloscopus_borealis),_Skaw_-_geograph.org.uk_-_3812845.jpg",
    "download": "https://upload.wikimedia.org/wikipedia/commons/d/d3/Arctic_Warbler_%28Phylloscopus_borealis%29%2C_Skaw_-_geograph.org.uk_-_3812845.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
    "description": "Arctic Warbler (Phylloscopus borealis), Skaw ",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w07",
    "type": "bitmap",
    "file": "assets/reference/w07.jpg",
    "title": "File:Yellow-browed warbler (Phylloscopus inornatus), Parc du Slot, Woluwé-St.-Lambert, Brussels (34053989676).jpg",
    "author": "Frank Vassen from Brussels, Belgium",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Yellow-browed_warbler_(Phylloscopus_inornatus),_Parc_du_Slot,_Woluw%C3%A9-St.-Lambert,_Brussels_(34053989676).jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8b/Yellow-browed_warbler_%28Phylloscopus_inornatus%29%2C_Parc_du_Slot%2C_Woluw%C3%A9-St.-Lambert%2C_Brussels_%2834053989676%29.jpg/1280px-Yellow-browed_warbler_%28Phylloscopus_inornatus%29%2C_Parc_du_Slot%2C_Woluw%C3%A9-St.-Lambert%2C_Brussels_%2834053989676%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "description": "Yellow-browed warbler (Phylloscopus inornatus), Parc du Slot, Woluwé-St.-Lambert, Brussels",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w08",
    "type": "bitmap",
    "file": "assets/reference/w08.jpg",
    "title": "File:Phylloscopus proregulus from iNaturalist photo 464132426.jpg",
    "author": "Zinogre (zinogre)",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Phylloscopus_proregulus_from_iNaturalist_photo_464132426.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/48/Phylloscopus_proregulus_from_iNaturalist_photo_464132426.jpg/1280px-Phylloscopus_proregulus_from_iNaturalist_photo_464132426.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "description": "Phylloscopus proregulus カラフトムシクイ",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w09",
    "type": "bitmap",
    "file": "assets/reference/w09.jpg",
    "title": "File:Hume's Warbler (Phylloscopus humei) (48828075393).jpg",
    "author": "gilgit2",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hume%27s_Warbler_(Phylloscopus_humei)_(48828075393).jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Hume%27s_Warbler_%28Phylloscopus_humei%29_%2848828075393%29.jpg/1280px-Hume%27s_Warbler_%28Phylloscopus_humei%29_%2848828075393%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "description": "Hume's Warbler (Phylloscopus humei) captured at Borit, Gojal, Gilgit-Baltistan, Pakistan with Canon EOS 7D Mark II",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  }
];
