window.AvianMediaCredits = [
  {
    "case": "02",
    "type": "bitmap",
    "file": "assets/reference/02-image.jpg",
    "title": "File:Bachstelze - Bergeronnette grise - White wagtail - Motacilla alba - 03.jpg",
    "author": "NorbertNagel",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bachstelze_-_Bergeronnette_grise_-_White_wagtail_-_Motacilla_alba_-_03.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/22/Bachstelze_-_Bergeronnette_grise_-_White_wagtail_-_Motacilla_alba_-_03.jpg/1280px-Bachstelze_-_Bergeronnette_grise_-_White_wagtail_-_Motacilla_alba_-_03.jpg",
    "description": "White Wagtail (Motacilla alba alba) with nesting material in its beak in the Mönchbruch nature reserve, Germany, in early April.",
    "change": "Wikimedia 1200px thumbnail; displayed with responsive crop"
  },
  {
    "case": "02",
    "type": "audio",
    "file": "assets/reference/02-audio.mp3",
    "title": "File:Motacilla alba - White Wagtail XC501786.mp3",
    "author": "Hannu Varkki",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Motacilla_alba_-_White_Wagtail_XC501786.mp3",
    "download": "https://upload.wikimedia.org/wikipedia/commons/4/42/Motacilla_alba_-_White_Wagtail_XC501786.mp3",
    "description": ":bird-seen:yes\nplayback-used:no\nCommon name: White Wagtail\nType: call\nGenus: Motacilla\nSpecies: alba\nLocation: Puotila, Helsinki, Uusimaa\nCountry: Finland\nElevation: 10 m",
    "change": "Unmodified reference recording; playback stops after 12 seconds"
  },
  {
    "case": "03",
    "type": "bitmap",
    "file": "assets/reference/03-image.jpg",
    "title": "File:Phoenicurus auroreus (male).JPG",
    "author": "Alpsdake",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Phoenicurus_auroreus_(male).JPG",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/Phoenicurus_auroreus_%28male%29.JPG/1280px-Phoenicurus_auroreus_%28male%29.JPG",
    "description": "Daurian Redstart (Phoenicurus auroreus), male in Aichi prefecture, Japan.",
    "change": "Wikimedia 1200px thumbnail; displayed with responsive crop"
  },
  {
    "case": "04",
    "type": "bitmap",
    "file": "assets/reference/04-image.jpg",
    "title": "File:Tree Sparrow August 2007 Osaka Japan.jpg",
    "author": "Laitche",
    "license": "Public domain",
    "licenseUrl": "",
    "source": "https://commons.wikimedia.org/wiki/File:Tree_Sparrow_August_2007_Osaka_Japan.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/98/Tree_Sparrow_August_2007_Osaka_Japan.jpg/1280px-Tree_Sparrow_August_2007_Osaka_Japan.jpg",
    "description": "Tree sparrow in Nagai Park, Osaka, Japan",
    "change": "Wikimedia 1200px thumbnail; displayed with responsive crop"
  },
  {
    "case": "04",
    "type": "audio",
    "file": "assets/reference/04-audio.mp3",
    "title": "File:Passer montanus - Eurasian Tree Sparrow XC347807.mp3",
    "author": "Derek Paulo",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Passer_montanus_-_Eurasian_Tree_Sparrow_XC347807.mp3",
    "download": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Passer_montanus_-_Eurasian_Tree_Sparrow_XC347807.mp3",
    "description": ":bird-seen:yes\nplayback-used:no\nCommon name: Eurasian Tree Sparrow\nType: call, song\nGenus: Passer\nSpecies: montanus\nLocation: CPAC, Murcia, Negros Occidental, Western Visayas\nCountry: Philippines\nElevation: 220 m",
    "change": "Unmodified reference recording; playback stops after 12 seconds"
  },
  {
    "case": "05",
    "type": "bitmap",
    "file": "assets/reference/05-image.jpg",
    "title": "File:Common Kingfisher Alcedo atthis.jpg",
    "author": "Andreas Trepte",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Common_Kingfisher_Alcedo_atthis.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cc/Common_Kingfisher_Alcedo_atthis.jpg/1280px-Common_Kingfisher_Alcedo_atthis.jpg",
    "description": "Common Kingfisher, Marburg, Germany",
    "change": "Wikimedia 1200px thumbnail; displayed with responsive crop"
  },
  {
    "case": "05",
    "type": "audio",
    "file": "assets/reference/05-audio.mp3",
    "title": "File:Alcedo atthis - Common Kingfisher XC476785.mp3",
    "author": "Marie-Lan Taÿ Pamart",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Alcedo_atthis_-_Common_Kingfisher_XC476785.mp3",
    "download": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Alcedo_atthis_-_Common_Kingfisher_XC476785.mp3",
    "description": ":Kingfisher calling in flight whilst crossing a lake (and passing the recorder), a former gravel pit reconverted as a nature reserve.\nBackground noises: unidentified immature Larus sp. (magna), commercial plane\nDistance: ~30m at closest\nEquipment: Tascam DR-100mkIII + Sennheiser ME-66/K6 + Rycote Windjammer\nEdits: -12dB high-pass filter at 4500Hz\nbird-seen:yes\nplayback-used:no\nCommon name: Common Kingfisher\nType: flight call\nGenus: Alcedo\nSpecies: atthis\nLocation: Trilbardou, Seine-et-Marne, Île-de-France\nCountry: France\nElevation: 40 m",
    "change": "Unmodified reference recording; playback stops after 12 seconds"
  },
  {
    "case": "06",
    "type": "bitmap",
    "file": "assets/reference/06-image.jpg",
    "title": "File:Light-vented Bulbul (Pycnonotus sinensis).jpg",
    "author": "Herbertkikoy",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Light-vented_Bulbul_(Pycnonotus_sinensis).jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/Light-vented_Bulbul_%28Pycnonotus_sinensis%29.jpg/1280px-Light-vented_Bulbul_%28Pycnonotus_sinensis%29.jpg",
    "description": "The Light-vented Bulbul (Pycnonotus sinensis) is an adaptable songbird commonly found in woodlands, parks, farmland, and urban gardens across East Asia. It feeds on fruits, nectar, insects, and small invertebrates, making it an important seed disperser and a natural helper in controlling insect populations. Its cheerful calls and active behavior make it easy to notice even in busy cities. This species thrives where trees and shrubs provide plenty of food and shelter.",
    "change": "Wikimedia 1200px thumbnail; displayed with responsive crop"
  },
  {
    "case": "w01",
    "type": "bitmap",
    "file": "assets/reference/w01.jpg",
    "title": "File:Yellow-browed Warbler by Tisha Mukherjee 05.jpg",
    "author": "Tisha Mukherjee",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Yellow-browed_Warbler_by_Tisha_Mukherjee_05.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3c/Yellow-browed_Warbler_by_Tisha_Mukherjee_05.jpg/1280px-Yellow-browed_Warbler_by_Tisha_Mukherjee_05.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "description": "Yellow-browed Warbler (Phylloscopus inornatus, Phylloscopidae, Passeriformes) in Rabindra Sarobar, West Bengal, India.",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w02",
    "type": "bitmap",
    "file": "assets/reference/w02.jpg",
    "title": "File:Hume's Warbler (Phylloscopus humei) - 48828586077.jpg",
    "author": "gilgit2",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hume%27s_Warbler_(Phylloscopus_humei)_-_48828586077.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/Hume%27s_Warbler_%28Phylloscopus_humei%29_-_48828586077.jpg/1280px-Hume%27s_Warbler_%28Phylloscopus_humei%29_-_48828586077.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "description": "Hume's Warbler (Phylloscopus humei) captured at Borit, Gojal, Gilgit-Baltistan, Pakistan with Canon EOS 7D Mark II",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w03",
    "type": "bitmap",
    "file": "assets/reference/w03.jpg",
    "title": "File:Pallas's leaf warbler (Phylloscopus proregulus) 2022.jpg",
    "author": "TRinaud",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pallas%27s_leaf_warbler_(Phylloscopus_proregulus)_2022.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/67/Pallas%27s_leaf_warbler_%28Phylloscopus_proregulus%29_2022.jpg/1280px-Pallas%27s_leaf_warbler_%28Phylloscopus_proregulus%29_2022.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "description": "Helgoland, Schleswig-Holstein, Germany",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w04",
    "type": "bitmap",
    "file": "assets/reference/w04.jpg",
    "title": "File:Dusky Warbler in Baruipur November 2025 by Tisha Mukherjee 03.jpg",
    "author": "Tisha Mukherjee",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Dusky_Warbler_in_Baruipur_November_2025_by_Tisha_Mukherjee_03.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Dusky_Warbler_in_Baruipur_November_2025_by_Tisha_Mukherjee_03.jpg/1280px-Dusky_Warbler_in_Baruipur_November_2025_by_Tisha_Mukherjee_03.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "description": "Dusky Warbler (Phylloscopus fuscatus, Phylloscopidae, Passeriformes) in Baruipur, West Bengal, India.",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w05",
    "type": "bitmap",
    "file": "assets/reference/w05.jpg",
    "title": "File:Radde's Warbler - Thailand S4E1407 (18645038584) (2).jpg",
    "author": "Francesco Veronesi from Italy",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Radde%27s_Warbler_-_Thailand_S4E1407_(18645038584)_(2).jpg",
    "download": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Radde%27s_Warbler_-_Thailand_S4E1407_%2818645038584%29_%282%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
    "description": "Radde's Warbler - Thailand_S4E1407",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w06",
    "type": "bitmap",
    "file": "assets/reference/w06.jpg",
    "title": "File:Arctic Warbler (Phylloscopus borealis), Skaw - geograph.org.uk - 3812845.jpg",
    "author": "Mike Pennington ",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Arctic_Warbler_(Phylloscopus_borealis),_Skaw_-_geograph.org.uk_-_3812845.jpg",
    "download": "https://upload.wikimedia.org/wikipedia/commons/d/d3/Arctic_Warbler_%28Phylloscopus_borealis%29%2C_Skaw_-_geograph.org.uk_-_3812845.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
    "description": "Arctic Warbler (Phylloscopus borealis), Skaw ",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w07",
    "type": "bitmap",
    "file": "assets/reference/w07.jpg",
    "title": "File:Yellow-browed warbler (Phylloscopus inornatus), Parc du Slot, Woluwé-St.-Lambert, Brussels (34053989676).jpg",
    "author": "Frank Vassen from Brussels, Belgium",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Yellow-browed_warbler_(Phylloscopus_inornatus),_Parc_du_Slot,_Woluw%C3%A9-St.-Lambert,_Brussels_(34053989676).jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8b/Yellow-browed_warbler_%28Phylloscopus_inornatus%29%2C_Parc_du_Slot%2C_Woluw%C3%A9-St.-Lambert%2C_Brussels_%2834053989676%29.jpg/1280px-Yellow-browed_warbler_%28Phylloscopus_inornatus%29%2C_Parc_du_Slot%2C_Woluw%C3%A9-St.-Lambert%2C_Brussels_%2834053989676%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "description": "Yellow-browed warbler (Phylloscopus inornatus), Parc du Slot, Woluwé-St.-Lambert, Brussels",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w08",
    "type": "bitmap",
    "file": "assets/reference/w08.jpg",
    "title": "File:Phylloscopus proregulus from iNaturalist photo 464132426.jpg",
    "author": "Zinogre (zinogre)",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Phylloscopus_proregulus_from_iNaturalist_photo_464132426.jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/48/Phylloscopus_proregulus_from_iNaturalist_photo_464132426.jpg/1280px-Phylloscopus_proregulus_from_iNaturalist_photo_464132426.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "description": "Phylloscopus proregulus カラフトムシクイ",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "w09",
    "type": "bitmap",
    "file": "assets/reference/w09.jpg",
    "title": "File:Hume's Warbler (Phylloscopus humei) (48828075393).jpg",
    "author": "gilgit2",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hume%27s_Warbler_(Phylloscopus_humei)_(48828075393).jpg",
    "download": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Hume%27s_Warbler_%28Phylloscopus_humei%29_%2848828075393%29.jpg/1280px-Hume%27s_Warbler_%28Phylloscopus_humei%29_%2848828075393%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "description": "Hume's Warbler (Phylloscopus humei) captured at Borit, Gojal, Gilgit-Baltistan, Pakistan with Canon EOS 7D Mark II",
    "change": "使用 Commons 提供的等比例缩略图；未加模糊、未生成或补画鉴别特征。"
  },
  {
    "case": "e02",
    "type": "audio",
    "file": "assets/reference/e02-audio.mp3",
    "title": "XC750002 Pallas's Leaf Warbler (Phylloscopus proregulus)",
    "author": "Geoff Carey",
    "license": "CC BY-NC-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    "source": "https://xeno-canto.org/750002",
    "download": "https://xeno-canto.org/750002/download",
    "description": "call；原录音地点：Nam Shan Tung, Sai Kung, Hong Kong, China。由香港观鸟会物种页引用。",
    "change": "截取开头最多18秒，转为MP3并做响度归一化与短淡入淡出；不改变音高或节奏。保留原许可。仅供非商业使用。",
    "duration": 18
  },
  {
    "case": "e03",
    "type": "audio",
    "file": "assets/reference/e03-audio.mp3",
    "title": "XC750688 Dusky Warbler (Phylloscopus fuscatus)",
    "author": "Geoff Carey",
    "license": "CC BY-NC-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    "source": "https://xeno-canto.org/750688",
    "download": "https://xeno-canto.org/750688/download",
    "description": "call；原录音地点：Pak Sha O, Sai Kung District, New Territories, Hong Kong, China。由香港观鸟会物种页引用。",
    "change": "截取开头最多18秒，转为MP3并做响度归一化与短淡入淡出；不改变音高或节奏。保留原许可。仅供非商业使用。",
    "duration": 12.984
  },
  {
    "case": "e04",
    "type": "audio",
    "file": "assets/reference/e04-audio.mp3",
    "title": "XC750628 Radde's Warbler (Phylloscopus schwarzi)",
    "author": "Geoff Carey",
    "license": "CC BY-NC-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    "source": "https://xeno-canto.org/750628",
    "download": "https://xeno-canto.org/750628/download",
    "description": "call；原录音地点：Pak Sha O, Sai Kung District, New Territories, Hong Kong, China。由香港观鸟会物种页引用。",
    "change": "截取开头最多18秒，转为MP3并做响度归一化与短淡入淡出；不改变音高或节奏。保留原许可。仅供非商业使用。",
    "duration": 18
  },
  {
    "case": "e05",
    "type": "audio",
    "file": "assets/reference/e05-audio.mp3",
    "title": "XC753456 Arctic Warbler (Phylloscopus borealis)",
    "author": "Geoff Carey",
    "license": "CC BY-NC-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    "source": "https://xeno-canto.org/753456",
    "download": "https://xeno-canto.org/753456/download",
    "description": "call, song；原录音地点：Pak Sha O, Sai Kung District, New Territories, Hong Kong, China。由香港观鸟会物种页引用。",
    "change": "保留完整录音，转为MP3并做响度归一化与短淡入淡出；不改变音高或节奏。保留原许可。仅供非商业使用。",
    "duration": 55.128
  },
  {
    "case": "e01",
    "type": "audio",
    "file": "assets/reference/e01-audio.mp3",
    "title": "File:Phylloscopus inornatus - Yellow-browed Warbler XC153463.mp3",
    "author": "Luis Ramos",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Phylloscopus_inornatus_-_Yellow-browed_Warbler_XC153463.mp3",
    "download": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Phylloscopus_inornatus_-_Yellow-browed_Warbler_XC153463.mp3?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "description": ":Aufnahme ist verkürzt. Bachhabitat mit Erlen im Bereich Schlupfenbuch/Prozessgraben. Individuum in den Kronen der Erlengruppe, aber nicht sichtbar.\nbird-seen:no\nplayback-used:no\nCommon name: Yellow-browed Warbler\nType: call\nGenus: Phylloscopus\nSpecies: inornatus\nLocation: Bodenseekreis (near  Kressbronn am Bodensee), Tübingen, Baden-Wurttemberg\nCountry: Germany\nElevation: 420 m",
    "change": "截取开头最多18秒，转为MP3并做响度归一化与短淡入淡出；不改变音高或节奏。保留原许可。",
    "duration": 5.59625
  },
  {
    "case": "e06",
    "type": "audio",
    "file": "assets/reference/e06-audio.mp3",
    "title": "File:Humes warbler nandi.ogg",
    "author": "Shyamal L.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Humes_warbler_nandi.ogg",
    "download": "https://upload.wikimedia.org/wikipedia/commons/6/63/Humes_warbler_nandi.ogg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "description": "Phylloscopus humei calling, Nandi Hills, Bangalore, India",
    "change": "截取开头最多18秒，转为MP3并做响度归一化与短淡入淡出；不改变音高或节奏。保留原许可。",
    "duration": 18
  },
  {
    "case": "e07",
    "type": "audio",
    "file": "assets/reference/e07-audio.mp3",
    "title": "XC750911 Eastern Crowned Warbler (Phylloscopus coronatus)",
    "author": "Geoff Carey",
    "license": "CC BY-NC-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    "source": "https://xeno-canto.org/750911",
    "download": "https://xeno-canto.org/750911/download",
    "description": "alarm call, call；原录音地点：Terneysky District, Primorsky Krai, Russian Federation。作为物种参考，不是本关虚构现场的录音。",
    "change": "截取开头最多24秒，转MP3、响度归一化和短淡入淡出，不改变音高节奏；衍生录音沿用原许可。",
    "derivative": true,
    "duration": 13.8,
    "originalSha256": "c3c297ce8493811864581ef39de4e4144b70b71f48301470b8d17033e207ab45",
    "sha256": "057e023acdceb5a65fa62e46b2011ac834cf169c88a60bfabc8087a654f58ab3"
  },
  {
    "case": "e08",
    "type": "audio",
    "file": "assets/reference/e08-audio.mp3",
    "title": "XC183391 Claudia's Leaf Warbler (Phylloscopus claudiae)",
    "author": "Frank Lambert",
    "license": "CC BY-NC-ND 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-nd/4.0/",
    "source": "https://xeno-canto.org/183391",
    "download": "https://xeno-canto.org/183391/download",
    "description": "call, song；原录音地点：Erlangshan, Sichuan, China。作为物种参考，不是本关虚构现场的录音。",
    "change": "原始 MP3 完整复制，字节未变；不剪辑、不归一化，保留原 BY-NC-ND 许可。",
    "derivative": false,
    "duration": 84.651325,
    "originalSha256": "836ec9d126007e16e99e5a4f844a4f2f1a643bedeb983a34d074551671b9e7ea",
    "sha256": "836ec9d126007e16e99e5a4f844a4f2f1a643bedeb983a34d074551671b9e7ea"
  },
  {
    "case": "e09",
    "type": "audio",
    "file": "assets/reference/e09-audio.mp3",
    "title": "XC752830 Two-barred Warbler (Phylloscopus plumbeitarsus)",
    "author": "Geoff Carey",
    "license": "CC BY-NC-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    "source": "https://xeno-canto.org/752830",
    "download": "https://xeno-canto.org/752830/download",
    "description": "call；原录音地点：Pak Sha O, Sai Kung District, New Territories, Hong Kong, China。作为物种参考，不是本关虚构现场的录音。",
    "change": "截取开头最多24秒，转MP3、响度归一化和短淡入淡出，不改变音高节奏；衍生录音沿用原许可。",
    "derivative": true,
    "duration": 22.056,
    "originalSha256": "e94444048c39605884803e0c05705b3d3284233901484e1ae89d81669b1f26cb",
    "sha256": "fafc79ed70edbcce94cbedf7be8999d988613e9f8e5f14377eeca91a385eaecc"
  },
  {
    "case": "e10",
    "type": "audio",
    "file": "assets/reference/e10-audio.mp3",
    "title": "XC756361 Pallas's Grasshopper Warbler (Helopsaltes certhiola)",
    "author": "Geoff Carey",
    "license": "CC BY-NC-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    "source": "https://xeno-canto.org/756361",
    "download": "https://xeno-canto.org/756361/download",
    "description": "call；原录音地点：Lok Ma Chau, New Territories, Hong Kong, China。作为物种参考，不是本关虚构现场的录音。",
    "change": "截取开头最多24秒，转MP3、响度归一化和短淡入淡出，不改变音高节奏；衍生录音沿用原许可。",
    "derivative": true,
    "duration": 24,
    "originalSha256": "04b3c4f38f3687698c32cf22faf685f0c5ad8a01cd66f8fa0efc143ee459e686",
    "sha256": "e6910868122193d167f7b51857ecb846dadaa67ced249f3b9a0a04b084690f60"
  },
  {
    "case": "e11",
    "type": "audio",
    "file": "assets/reference/e11-audio.mp3",
    "title": "XC757067 Chinese Bush Warbler (Locustella tacsanowskia)",
    "author": "Geoff Carey",
    "license": "CC BY-NC-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    "source": "https://xeno-canto.org/757067",
    "download": "https://xeno-canto.org/757067/download",
    "description": "call；原录音地点：Laoye Shan, Datong, Qinghai, China。作为物种参考，不是本关虚构现场的录音。",
    "change": "截取开头最多24秒，转MP3、响度归一化和短淡入淡出，不改变音高节奏；衍生录音沿用原许可。",
    "derivative": true,
    "duration": 24,
    "originalSha256": "ecf61823450f2083835530b230857dc493b180c2f68333cea9cf6e9d82e00f3d",
    "sha256": "82006b619565427fa31b6628ebd27151d7965a94e3b13f1a6c56752d4f20a19c"
  },
  {
    "case": "e12",
    "type": "audio",
    "file": "assets/reference/e12-audio.mp3",
    "title": "XC395914 Lanceolated Warbler (Locustella lanceolata)",
    "author": "Jarmo Pirhonen",
    "license": "CC BY-NC-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    "source": "https://xeno-canto.org/395914",
    "download": "https://xeno-canto.org/395914/download",
    "description": "call；原录音地点：Tmat Boey, Preah Vihear Province, Cambodia。作为物种参考，不是本关虚构现场的录音。",
    "change": "截取开头最多24秒，转MP3、响度归一化和短淡入淡出，不改变音高节奏；衍生录音沿用原许可。",
    "derivative": true,
    "duration": 24,
    "originalSha256": "426eda1c8f933fe57f67667e2b78d6e7cdb03c300b94df6232b7990fd80a03fe",
    "sha256": "b47a9642b90969a167822e792c3ca62b302edbee76a39b48b5cbbb5ec9cff348"
  },
  {
    "case": "e13",
    "type": "audio",
    "file": "assets/reference/e13-audio.mp3",
    "title": "XC757073 Baikal Bush Warbler (Locustella davidi)",
    "author": "Geoff Carey",
    "license": "CC BY-NC-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    "source": "https://xeno-canto.org/757073",
    "download": "https://xeno-canto.org/757073/download",
    "description": "call；原录音地点：Mai Po Nature Reserve, New Territories, Hong Kong, China。作为物种参考，不是本关虚构现场的录音。",
    "change": "截取开头最多24秒，转MP3、响度归一化和短淡入淡出，不改变音高节奏；衍生录音沿用原许可。",
    "derivative": true,
    "duration": 24,
    "originalSha256": "335b73ad20f483aa03381dd0876c0e071e4cd6c1ac1a88cefbcd3a981ff57e2f",
    "sha256": "5f8d1df7d2b559b12b1708b3ae1a13781f4128d1fdc36e64954622aa20335a20"
  },
  {
    "case": "e14",
    "type": "audio",
    "file": "assets/reference/e14-audio.mp3",
    "title": "XC748796 Asian Stubtail (Urosphena squameiceps)",
    "author": "Geoff Carey",
    "license": "CC BY-NC-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    "source": "https://xeno-canto.org/748796",
    "download": "https://xeno-canto.org/748796/download",
    "description": "call；原录音地点：Pak Sha O, Sai Kung District, New Territories, Hong Kong, China。作为物种参考，不是本关虚构现场的录音。",
    "change": "截取开头最多24秒，转MP3、响度归一化和短淡入淡出，不改变音高节奏；衍生录音沿用原许可。",
    "derivative": true,
    "duration": 24,
    "originalSha256": "e6a91d36c87e38ba5877177dd6a50ef4b9e0ee3390632ddc61f45b7707b670d8",
    "sha256": "d70a3d73f7da192f07e10e0c76e6ed383011d0c034f9a0761d208a891a77314c"
  },
  {
    "case": "e15",
    "type": "audio",
    "file": "assets/reference/e15-audio.mp3",
    "title": "XC731529 Olive-backed Pipit (Anthus hodgsoni yunnanensis)",
    "author": "Geoff Carey",
    "license": "CC BY-NC-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    "source": "https://xeno-canto.org/731529",
    "download": "https://xeno-canto.org/731529/download",
    "description": "flight call；原录音地点：Pak Sha O, Sai Kung District, New Territories, Hong Kong, China。作为物种参考，不是本关虚构现场的录音。",
    "change": "截取开头最多24秒，转MP3、响度归一化和短淡入淡出，不改变音高节奏；衍生录音沿用原许可。",
    "derivative": true,
    "duration": 16.512,
    "originalSha256": "39d386b1a215b03e3bcc194b3446cb95b8360b11f5a8c6dc5c7e9d471f48bcb2",
    "sha256": "a5b15f1acea95adf2fb110964cc9c3b6ef02d84433c7d0120ef019523a354955"
  },
  {
    "case": "e16",
    "type": "audio",
    "file": "assets/reference/e16-audio.mp3",
    "title": "XC162596 Blyth's Pipit (Anthus godlewskii)",
    "author": "Patrick Franke",
    "license": "CC BY-NC-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/3.0/",
    "source": "https://xeno-canto.org/162596",
    "download": "https://xeno-canto.org/162596/download",
    "description": "call, call in flight, excitement call；原录音地点：Telmen Nuur, Mongolia。作为物种参考，不是本关虚构现场的录音。",
    "change": "截取开头最多24秒，转MP3、响度归一化和短淡入淡出，不改变音高节奏；衍生录音沿用原许可。",
    "derivative": true,
    "duration": 8.759075,
    "originalSha256": "0228d9f66507e334e2a46e6ef27280341355a405f9f49c9cd9cea1f8397aa9f8",
    "sha256": "679fa5a0bac71c19c7bf297d7ba1627e3d98a1596fe16d4e7469ed0c72e441b4"
  },
  {
    "case": "e17",
    "type": "audio",
    "file": "assets/reference/e17-audio.mp3",
    "title": "XC731290 Richard's Pipit (Anthus richardi)",
    "author": "Geoff Carey",
    "license": "CC BY-NC-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    "source": "https://xeno-canto.org/731290",
    "download": "https://xeno-canto.org/731290/download",
    "description": "flight call；原录音地点：Sham Chung, Sai Kung West Country Park, China。作为物种参考，不是本关虚构现场的录音。",
    "change": "截取开头最多24秒，转MP3、响度归一化和短淡入淡出，不改变音高节奏；衍生录音沿用原许可。",
    "derivative": true,
    "duration": 10.032,
    "originalSha256": "74ede1fbdd8bd0dd4151fc85040f44c4bfbf93b497de0d3a3fcdf715ed292d31",
    "sha256": "a34aa4a940eb8faade5e940bf6b11b359fee8e6432ebd75347a319da9d9d9e16"
  },
  {
    "case": "e18",
    "type": "audio",
    "file": "assets/reference/e18-audio.mp3",
    "title": "XC435101 Water Pipit (Anthus spinoletta blakistoni)",
    "author": "Patrick Franke",
    "license": "CC BY-NC-ND 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-nd/4.0/",
    "source": "https://xeno-canto.org/435101",
    "download": "https://xeno-canto.org/435101/download",
    "description": "flight call；原录音地点：Bayankhongorijn Khukh Nuur, Mongolia。作为物种参考，不是本关虚构现场的录音。",
    "change": "原始 MP3 完整复制，字节未变；不剪辑、不归一化，保留原 BY-NC-ND 许可。",
    "derivative": false,
    "duration": 2.037551,
    "originalSha256": "353e0d527aa2819018df54da87e99bbf70ebe1bca6d972a65418b516b6566660",
    "sha256": "353e0d527aa2819018df54da87e99bbf70ebe1bca6d972a65418b516b6566660"
  },
  {
    "case": "e19",
    "type": "audio",
    "file": "assets/reference/e19-audio.mp3",
    "title": "XC731785 Red-throated Pipit (Anthus cervinus)",
    "author": "Geoff Carey",
    "license": "CC BY-NC-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    "source": "https://xeno-canto.org/731785",
    "download": "https://xeno-canto.org/731785/download",
    "description": "flight call；原录音地点：Long Valley, New Territories, Hong Kong, China。作为物种参考，不是本关虚构现场的录音。",
    "change": "截取开头最多24秒，转MP3、响度归一化和短淡入淡出，不改变音高节奏；衍生录音沿用原许可。",
    "derivative": true,
    "duration": 13.704,
    "originalSha256": "521df6dd8340a7b046f94f7119ca57045994b68f27f8dfbaeed689dbc928de2b",
    "sha256": "50c60e2fd9e47c29104cd0bf123cb5838703612653aec17f92496015223a4ab1"
  },
  {
    "case": "e20",
    "type": "audio",
    "file": "assets/reference/e20-audio.mp3",
    "title": "XC622932 Buff-bellied Pipit (Anthus rubescens japonicus)",
    "author": "Jens Kirkeby",
    "license": "CC BY-NC-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    "source": "https://xeno-canto.org/622932",
    "download": "https://xeno-canto.org/622932/download",
    "description": "flight call；原录音地点：Trevozhnaya, Golden Ridge, Anadyrsky District, Chukotka Autonomous Okrug, Russian Federation。作为物种参考，不是本关虚构现场的录音。",
    "change": "截取开头最多24秒，转MP3、响度归一化和短淡入淡出，不改变音高节奏；衍生录音沿用原许可。",
    "derivative": true,
    "duration": 12.1409,
    "originalSha256": "e83f27e75f6e36ba23b075308deb526fa95f32740fb0d7d0b3177ad819f3c72f",
    "sha256": "6caffb692a6dca2a025db73a57ba19dbe7442669cda21c35509e3ccffaf2443e"
  }
];
