(function(root){
 'use strict';
 const {clamp,wrap,random,bearing,distance,byId,habitats,stations}=Avian;
 function fit(canvas){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);const w=Math.round(r.width*d),h=Math.round(r.height*d);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}const c=canvas.getContext('2d');c.setTransform(d,0,0,d,0,0);return {c,w:r.width,h:r.height,d};}
 function path(c,points,fill){c.beginPath();points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();c.fillStyle=fill;c.fill();}
 function bird(c,s,x,y,size,pose='perch',thermal=false,t=0){c.save();c.translate(x,y);c.scale(size,size);const long=s.id==='egret'||s.id==='night';c.fillStyle=thermal?'#fed98a':s.color;c.strokeStyle=thermal?'#ffc782':s.accent;c.lineWidth=.6;
   if(pose==='fly'){c.beginPath();c.moveTo(-1.2,0);c.quadraticCurveTo(-3,-3.8*Math.sin(t*9)-1,-4,-1);c.quadraticCurveTo(-2,-.2,0,.3);c.quadraticCurveTo(2,-.2,4,-1);c.quadraticCurveTo(2,-3.8*Math.sin(t*9)-1,1,0);c.closePath();c.fill();c.beginPath();c.ellipse(0,.1,.7,.35,0,0,Math.PI*2);c.fill();}
   else {c.beginPath();c.ellipse(0,0,long?1.5:1.2,long?.85:.72,-.18,0,Math.PI*2);c.fill();if(long){c.beginPath();c.lineWidth=s.id==='egret'?.48:.8;c.strokeStyle=c.fillStyle;c.moveTo(.65,-.2);c.bezierCurveTo(1.3,-.8,.6,-1.5,1.4,-2.2);c.stroke();}const hx=long?1.5:1,hy=long?-2.2:-.8;c.beginPath();c.arc(hx,hy,long?.42:.48,0,Math.PI*2);c.fill();path(c,[[hx+.3,hy-.1],[hx+(s.id==='kingfisher'?1.4:.95),hy+.02],[hx+.35,hy+.16]],thermal?'#fff0a4':s.accent);path(c,[[-.7,.1],[-2.1,s.id==='robin'?-1.1:.65],[-.7,.45]],c.fillStyle);c.fillStyle=thermal?'#f19f56':s.accent;c.beginPath();c.ellipse(-.1,.12,.85,.38,-.2,0,Math.PI*2);c.fill();if(s.id==='bulbul'||s.id==='robin'){c.fillStyle=s.accent;c.fillRect(hx-.35,hy-.15,.32,.24);}c.fillStyle='#142d2e';c.beginPath();c.arc(hx+.13,hy-.1,.075,0,Math.PI*2);c.fill();c.strokeStyle=thermal?'#dc8453':'#4b5b49';c.lineWidth=.12;for(let i=0;i<2;i++){c.beginPath();c.moveTo(-.2+i*.65,.6);c.lineTo(-.35+i*.65,long?2.2:1.05);c.lineTo(.05+i*.65,long?2.2:1.05);c.stroke();}}
   c.restore();
 }
 class Renderer {
  constructor(scene,map,spectrum){this.scene=scene;this.map=map;this.spectrum=spectrum;const rng=random(419);this.trees=Array.from({length:95},()=>({a:rng()*360,size:45+rng()*105,depth:rng(),seed:rng()*999}));this.reeds=Array.from({length:160},()=>({a:rng()*360,h:20+rng()*75,bend:rng()*20}));this.spectrumLast=0;this.specBuffer=document.createElement('canvas');this.specBuffer.width=256;this.specBuffer.height=128;}
  draw(world,state,time){const {c,w,h}=fit(this.scene);if(!w)return;const {yaw,mode,zoom}=state;const fov=zoom?110/6:110;const light=clamp(Math.sin((world.minute/60-5)*Math.PI/14),0,1);const dawn=clamp(1-Math.abs(world.minute/60-6.5)/3,0,1);const night=world.minute<290||world.minute>1190;
   if(mode==='eyes'){c.fillStyle='#08191e';c.fillRect(0,0,w,h);const g=c.createRadialGradient(w/2,h*.5,5,w/2,h*.5,w*.6);g.addColorStop(0,'#173332');g.addColorStop(1,'#08191e');c.fillStyle=g;c.fillRect(0,0,w,h);c.strokeStyle='#67867a20';for(let r=60;r<360;r+=60){c.beginPath();c.arc(w/2,h*.52,r,0,Math.PI*2);c.stroke();}c.fillStyle='#b7c7b680';c.font='11px sans-serif';c.textAlign='center';c.fillText('让声音勾勒世界的边界',w/2,h*.79);return;}
   const thermal=mode==='thermal';const sky=c.createLinearGradient(0,0,0,h);sky.addColorStop(0,thermal?'#162437':night?'#162f3b':dawn>.3?'#a9b9a7':'#94b8b7');sky.addColorStop(.5,thermal?'#263646':night?'#526566':'#dae0be');sky.addColorStop(1,thermal?'#152d3b':'#769f92');c.fillStyle=sky;c.fillRect(0,0,w,h);
   const sunX=w*.67-wrap(yaw-25)/fov*w*.3;c.fillStyle=thermal?'#284354':night?'#c1d3bf':'#f4e9c4';c.globalAlpha=.7;c.beginPath();c.arc(sunX,h*.22,night?14:28,0,Math.PI*2);c.fill();c.globalAlpha=1;
   for(let layer=0;layer<3;layer++){const pts=[[-10,h]];for(let x=-10;x<w+20;x+=12){const a=x/w*3+yaw/85;pts.push([x,h*(.39+layer*.055)+Math.sin(a*2.5+layer)*h*.032+Math.sin(a*7+layer)*h*.01]);}pts.push([w+10,h]);path(c,pts,thermal?['#2d3f49','#253c43','#1d333c'][layer]:night?['#3d5b5d','#355755','#294e4c'][layer]:['#93afa0','#779988','#5d8677'][layer]);}
   for(const tree of this.trees){let angle=wrap(tree.a-yaw);if(Math.abs(angle)>fov*.7)continue;const x=w/2+angle/fov*w,base=h*(.46+tree.depth*.11),size=tree.size*(.45+tree.depth*.35)*(zoom?1.9:1);this.tree(c,x,base,size,thermal?'#1b333b':night?'#234841':tree.depth>.5?'#416e5b':'#618677',tree.seed);}
   const bank=h*.62;const water=c.createLinearGradient(0,bank,0,h);water.addColorStop(0,thermal?'#183844':night?'#446d6a':'#b1c8b5');water.addColorStop(1,thermal?'#0b2631':night?'#21474b':'#517f76');c.beginPath();c.moveTo(0,bank);c.bezierCurveTo(w*.25,h*.51,w*.39,h*.69,w*.55,h*.58);c.bezierCurveTo(w*.8,h*.52,w*.84,h*.6,w,bank);c.lineTo(w,h);c.lineTo(0,h);c.closePath();c.fillStyle=water;c.fill();
   c.save();c.globalAlpha=.19;c.strokeStyle=thermal?'#629b9e':'#eff3ca';c.lineWidth=.7;for(let i=0;i<60;i++){let yy=h*(.62+(i/60)*.38),xx=((i*193.71+Math.sin(time*.3+i)*12-yaw*2)%w+w)%w;c.beginPath();c.moveTo(xx,yy);c.lineTo(xx+10+i*.45,yy);c.stroke();}c.restore();
   path(c,[[0,h*.74],[w*.1,h*.67],[w*.22,h*.72],[w*.27,h*.81],[w*.37,h*.89],[w*.43,h],[0,h]],thermal?'#173638':night?'#183c36':'#577963');
   path(c,[[w,h*.67],[w*.88,h*.71],[w*.84,h*.77],[w*.92,h*.85],[w*.94,h],[w,h]],thermal?'#1c3b39':night?'#25413a':'#718969');
   for(const b of [...world.noises,...world.birds]){const a=wrap(bearing(world.player,b)-yaw),dist=distance(world.player,b);if(Math.abs(a)>fov*.6||dist>220)continue;const x=w/2+a/fov*w,y=h*(.58-b.height*.009)+Math.sin(b.phase||0)*2;const s=byId[b.species];const visible=s?b.exposure:.7;if(visible<.23)continue;let size=clamp(240/(dist+30),1.5,5)*(zoom?6:1)*(s?.size||.8);
     if(thermal&&(dist>140||visible<.3))continue;
     c.globalAlpha=thermal?.9:clamp(visible*world.env.visibility,.22,1);
     if(s){if(b.state!=='fly'&&b.height>1){c.strokeStyle=thermal?'#2b4b4d':'#3a5b45';c.lineWidth=zoom?3:1;c.beginPath();c.moveTo(x-size*5,y+size*1.2);c.lineTo(x+size*2,y+size*1.05);c.stroke();}bird(c,s,x,y,size,b.state,thermal,time);if(visible<.44&&!thermal){c.fillStyle='#507562b0';c.beginPath();c.ellipse(x,y+2,size*4,size*.7,0,0,Math.PI*2);c.fill();}}
     else if(!thermal||b.type==='squirrel'){c.fillStyle=thermal?'#f7bd6a':b.type==='bag'?'#273e40':'#728978';if(b.type==='bag'){path(c,[[x-4*size,y],[x-2*size,y-2*size],[x+size,y-size],[x+2*size,y+size],[x-size,y+2*size]],c.fillStyle);}else if(b.type==='squirrel'){c.beginPath();c.ellipse(x,y,size*1.5,size*.8,0,0,Math.PI*2);c.fill();c.beginPath();c.arc(x-size*1.5,y-size*.9,size,0,Math.PI*2);c.fill();}else if(b.type==='brake'){c.strokeStyle='#3c5650';c.lineWidth=Math.max(1,size*.2);for(const dx of [-2,2]){c.beginPath();c.arc(x+dx*size,y+size,size,0,Math.PI*2);c.stroke();}c.beginPath();c.moveTo(x-2*size,y+size);c.lineTo(x-size,y-size);c.lineTo(x+2*size,y+size);c.lineTo(x,y+size);c.lineTo(x+size,y-size);c.lineTo(x+2*size,y-size);c.stroke();}else if(b.type==='wind'){c.strokeStyle='#4c7050';c.lineWidth=Math.max(1,size*.2);c.beginPath();c.moveTo(x-3*size,y+size);c.lineTo(x+3*size,y-size);c.stroke();for(let i=0;i<4;i++){c.beginPath();c.ellipse(x+(i-1.5)*size,y+Math.sin(time*2+i)*size,size*.8,size*.3,-.5,0,Math.PI*2);c.fill();}}}
     c.globalAlpha=1;
   }
   const fog=world.weather==='mist'?.25:world.weather==='rain'?.1:.08;c.fillStyle=`rgba(216,228,204,${thermal?0:fog})`;c.fillRect(0,h*.35,w,h*.36);
   for(const r of this.reeds){const a=wrap(r.a-yaw);if(Math.abs(a)>fov*.65)continue;const x=w/2+a/fov*w;if(x>w*.26&&x<w*.87)continue;const base=h+10,height=r.h*(zoom?1.3:1),sway=Math.sin(time*.9+r.a)*world.env.wind*1.2;c.strokeStyle=thermal?'#264d45':night?'#244a3c':'#425f43';c.lineWidth=1.2;c.beginPath();c.moveTo(x,base);c.quadraticCurveTo(x+sway,base-height*.6,x+sway+r.bend,base-height);c.stroke();c.strokeStyle=thermal?'#47674c':'#6d7147';c.lineWidth=3;c.beginPath();c.moveTo(x+sway+r.bend,base-height);c.lineTo(x+sway+r.bend+2,base-height-13);c.stroke();}
   if(world.weather==='rain'){c.strokeStyle='#e0edde38';c.lineWidth=.7;for(let i=0;i<60;i++){const x=(i*139+time*23)%w,y=(i*43+time*120)%h;c.beginPath();c.moveTo(x,y);c.lineTo(x-3,y+13);c.stroke();}}
   if(!thermal&&night){c.fillStyle='#09212d55';c.fillRect(0,0,w,h);}
   if(zoom){c.fillStyle='#07171bb5';c.beginPath();c.rect(0,0,w,h);c.ellipse(w/2,h*.52,Math.min(w*.48,h*.69),h*.47,0,0,Math.PI*2,true);c.fill('evenodd');}
   if(thermal){c.font='9px monospace';c.fillStyle='#e9c998';c.fillText('THERMAL · 温暖目标 ≠ 鸟',20,h-60);}
  }
  tree(c,x,y,size,color,seed){c.strokeStyle=color;c.lineWidth=size*.045;c.beginPath();c.moveTo(x,y);c.lineTo(x-size*.06,y-size*.82);c.stroke();const rng=random(seed);c.fillStyle=color;for(let i=0;i<7;i++){c.beginPath();c.ellipse(x+(rng()-.5)*size*.55,y-size*(.4+rng()*.45),size*(.18+rng()*.13),size*(.15+rng()*.2),rng(),0,Math.PI*2);c.fill();}}
  drawMap(world,state){const {c,w,h}=fit(this.map);if(!w)return;const sx=w/1000,sy=h/800;c.fillStyle='#223c35';c.fillRect(0,0,w,h);c.strokeStyle='#aec9a80d';for(let x=0;x<w;x+=18){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=0;y<h;y+=18){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}c.fillStyle='#426b63';c.beginPath();c.ellipse(w*.56,h*.52,w*.21,h*.35,-.4,0,Math.PI*2);c.fill();c.fillStyle='#70846465';c.beginPath();c.ellipse(w*.4,h*.57,w*.12,h*.25,-.7,0,Math.PI*2);c.fill();c.setLineDash([3,4]);c.strokeStyle='#b8bd9760';c.beginPath();stations.forEach((s,i)=>i?c.lineTo(s.x*sx,s.y*sy):c.moveTo(s.x*sx,s.y*sy));c.stroke();c.setLineDash([]);
   c.font='8px sans-serif';c.textAlign='center';for(const a of habitats){c.fillStyle=state.prediction?.habitat===a.id?'#e7ac78':'#c5d5b49c';c.fillText(a.name,a.x*sx,(a.y-50)*sy);}
   for(const s of stations){const x=s.x*sx,y=s.y*sy;c.fillStyle=s.id===world.player.id?'#d9e6be':'#506f5c';c.strokeStyle='#d9e6be';c.beginPath();c.arc(x,y,4,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#e2e9ce';c.fillText(s.name.slice(0,2),x,y+14);}
   const px=world.player.x*sx,py=world.player.y*sy,rad=state.yaw*Math.PI/180;c.save();c.translate(px,py);c.rotate(rad);path(c,[[0,0],[-17,-38],[17,-38]],'#daedbe19');c.strokeStyle='#e6edc58c';c.beginPath();c.moveTo(0,0);c.lineTo(0,-33);c.stroke();c.restore();
   if(state.selected){const ev=world.events.find(e=>e.entityId===state.selected);if(ev){c.save();c.translate(px,py);c.rotate(ev.bearing*Math.PI/180);c.setLineDash([2,3]);c.strokeStyle='#e3aa76';c.beginPath();c.moveTo(0,-8);c.lineTo(0,-55);c.stroke();c.restore();}}
   c.textAlign='left';c.fillStyle='#bfd0b9';c.font='8px monospace';c.fillText('N ↑',9,14);
  }
  drawSpectrum(audio,t){if(t-this.spectrumLast<1/32)return;this.spectrumLast=t;const {c,w,h}=fit(this.spectrum);if(!w)return;const b=this.specBuffer,bc=b.getContext('2d');bc.drawImage(b,-1,0);bc.fillStyle='#112728';bc.fillRect(255,0,1,128);const data=audio.frequency();if(data&&audio.ctx.state==='running'){for(let y=0;y<128;y++){const f=(127-y)/127*8000,bin=Math.round(f/(audio.ctx.sampleRate/1024)),v=(data[bin]||0)/255;bc.fillStyle=`rgb(${Math.round(19+v*173)},${Math.round(39+v*173)},${Math.round(40+v*85)})`;bc.fillRect(255,y,1,1);}}c.drawImage(b,0,0,w,h);c.strokeStyle='#aacba514';for(let i=1;i<4;i++){c.beginPath();c.moveTo(0,h*i/4);c.lineTo(w,h*i/4);c.stroke();}}
 }
 root.AvianRenderer=Renderer;root.drawAvianBird=bird;
})(globalThis);
