const {chromium,webkit}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {cases}=require('../challenge-data.js');
(async()=>{const browser=await (process.env.TEST_WEBKIT?webkit:chromium).launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1100},deviceScaleFactor:1,acceptDownloads:true});const p=await context.newPage(),errors=[],resources=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().includes('/assets/')&&r.status()>=400)resources.push({url:r.url(),status:r.status()});});fs.mkdirSync('evidence',{recursive:true});
 const base=process.env.BASE_URL||'http://127.0.0.1:18876/';await p.goto(base);await p.waitForSelector('#challenge-view:not([hidden])');assert.equal(await p.locator('#field-view').isVisible(),false);assert.equal(await p.locator('#answer-reveal').isVisible(),false);assert.equal(await p.locator('#candidates').isVisible(),false);assert.equal(await p.locator('#submit-guess').isDisabled(),true);
 if(!process.env.TEST_WEBKIT)await p.screenshot({path:'evidence/v2-desktop-start.png',fullPage:true});
 for(let i=0;i<cases.length;i++){
  const c=cases[i];await p.click(`[data-case="${i}"]`);assert.equal(await p.locator('#answer-reveal').isVisible(),false);await p.click('#observe-form');if(c.image){await p.waitForFunction(()=>{const img=document.getElementById('case-photo');return img.complete&&img.naturalWidth>0;});assert.equal(await p.locator('#case-photo').isVisible(),true);}else assert.equal(await p.locator('#case-photo').isVisible(),false);
  if(i===0&&!process.env.TEST_WEBKIT)await p.screenshot({path:'evidence/v2-photo.png',fullPage:true});await p.click('#observe-behavior');await p.click('#observe-sound');if(c.audio){await p.waitForFunction(()=>!document.getElementById('reference-recording').paused&&document.getElementById('reference-recording').currentTime>.15);assert.equal(await p.locator('#stop-recording').isVisible(),true);}else{assert.equal(await p.locator('#stop-recording').isVisible(),false);assert.match(await p.textContent('#recording-status'),/没有/);}
  await p.click('[data-clue="form"]');await p.locator('input[name="bird-answer"]').filter({visible:true}).evaluateAll((els,v)=>{if(!els.some(e=>e.value===v))throw new Error('Missing choice');},c.answer);await p.getByLabel(c.answer,{exact:true}).check();await p.fill('#guess-reason','依据实际看到的局部特征，并保留缺失信息。');await p.click('#submit-guess');await p.waitForSelector('#answer-reveal:not([hidden])');assert.match(await p.textContent('#result-stamp'),c.open?/暂不定种/:/判断吻合/);assert.equal(await p.locator('#submit-guess').isDisabled(),true);assert.equal(await p.locator('#reference-recording').evaluate(a=>a.paused),true);assert.equal(await p.locator('#comparison-list .comparison-row').count(),4);
  if(c.open&&!process.env.TEST_WEBKIT)await p.screenshot({path:'evidence/v2-open-case.png',fullPage:true});
 }
 // Wrong confident answer must not pass; repeats add attempts rather than overwrite history.
 await p.click('[data-case="0"]');await p.click('#observe-form');await p.getByLabel('树麻雀',{exact:true}).check();await p.getByLabel('很确定',{exact:true}).check();await p.click('#submit-guess');assert.match(await p.textContent('#result-title'),/换个方向/);assert.match(await p.textContent('#reason-feedback'),/把握很高/);if(!process.env.TEST_WEBKIT)await p.screenshot({path:'evidence/v2-wrong-answer.png',fullPage:true});assert.equal(await p.textContent('#quiz-record-count'),'7');await p.reload();assert.equal(await p.textContent('#quiz-record-count'),'7');
 await p.click('#quiz-history-button');assert.equal(await p.locator('.guess-history-item').count(),7);await p.locator('#quiz-history .close-dialog').click();
 const dl=p.waitForEvent('download');await p.click('#export-guesses');const download=await dl;await download.saveAs('evidence/v2-export-test.json');assert.equal(JSON.parse(fs.readFileSync('evidence/v2-export-test.json')).records.length,7);
 // Audio stops on mode changes; free observation remains available and separate.
 await p.click('#observe-sound');await p.waitForFunction(()=>!document.getElementById('reference-recording').paused);await p.click('[data-tab="field"]');assert.equal(await p.locator('#reference-recording').evaluate(a=>a.paused),true);await p.click('#start');await p.waitForSelector('.signal');await p.click('[data-tab="challenge"]');await p.waitForFunction(()=>document.getElementById('audio-state').textContent==='PAUSED');
 await p.setViewportSize({width:390,height:844});await p.click('[data-case="2"]');await p.click('#observe-form');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(!process.env.TEST_WEBKIT)await p.screenshot({path:'evidence/v2-mobile.png',fullPage:true});await p.getByLabel('树麻雀',{exact:true}).check();await p.click('#submit-guess');assert.match(await p.textContent('#result-stamp'),/判断吻合/);
 // Source failure must not manufacture successful audio evidence.
 await p.click('[data-case="0"]');await p.route('**/02-audio.mp3',r=>r.abort());await p.click('#observe-sound');await p.waitForFunction(()=>/失败|未能/.test(document.getElementById('recording-status').textContent));assert.equal(await p.locator('[data-clue="sound"]').isDisabled(),true);await p.unroute('**/02-audio.mp3');
 if(!process.env.BASE_URL){const off=await context.newPage();off.on('pageerror',e=>errors.push(e.message));if(!process.env.TEST_WEBKIT)await context.setOffline(true);await off.goto('file://'+path.resolve('芦汀观测站.html'));if(process.env.TEST_WEBKIT)await context.setOffline(true);await off.click('#observe-form');await off.waitForFunction(()=>document.getElementById('case-photo').naturalWidth>0);await off.click('#observe-sound');await off.waitForFunction(()=>document.getElementById('reference-recording').currentTime>.15);}
 assert.deepEqual(errors,[]);assert.deepEqual(resources,[]);const label=process.env.TEST_WEBKIT?'webkit':process.env.BASE_URL?'online':'chromium';fs.writeFileSync(`evidence/v2-${label}-results.json`,JSON.stringify({passed:true,engine:label,url:base,checks:['six distinct cases','answer hidden before submission','five real photos load','three real recordings play','missing audio explicit','correct and wrong feedback','open case does not force a species','confidence feedback','evidence selection','repeat attempts','reload persistence','history and export','mode switch stops sound','legacy simulation starts','390px no horizontal overflow','failed recording does not count as heard','offline embedded picture and sound'],errors,resources},null,2));await browser.close();console.log('Challenge browser acceptance passed:',label);
})().catch(e=>{console.error(e);process.exit(1);});
