const {chromium,webkit}=require(process.env.PLAYWRIGHT_PATH||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const D=require('../encounter-data.js');
(async()=>{
 const engine=process.env.TEST_WEBKIT?'webkit':'chromium',browser=await(engine==='webkit'?webkit:chromium).launch({headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});const p=await context.newPage(),errors=[],bad=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().includes('/assets/')&&r.status()>=400)bad.push(r.url());});
 const base=process.env.BASE_URL||'http://127.0.0.1:18876/';fs.mkdirSync('evidence',{recursive:true});await p.goto(base);
 assert.equal(await p.locator('#encounter-view').isVisible(),true);assert.equal(await p.locator('[data-enc-track]').count(),11);assert.equal(await p.locator('[data-enc-case]').count(),9);assert.equal(await p.evaluate(()=>getComputedStyle(document.querySelector('.enc-tracks')).gridTemplateColumns.split(' ').length),5);
 if(engine==='chromium')await p.screenshot({path:'evidence/v6-entry.png',fullPage:true});
 for(const [track,meta] of Object.entries(D.tracks)){
  await p.click('#enc-track-'+track);const pool=D.pool(track);assert.equal(await p.locator('[data-enc-case]').count(),pool.length);assert.ok((await p.textContent('#enc-track-description')).trim().length>0);assert.equal(await p.locator('#enc-track-'+track).getAttribute('aria-pressed'),'true');
  const c=pool.at(-1);await p.click(`[data-enc-case="${D.scenes.indexOf(c)}"]`);assert.equal(await p.locator('[name="enc-answer"]').count(),pool.length+1);
  assert.ok(c.photo,`${c.id} needs a reference photo or labelled teaching illustration`);
  await p.click('#enc-optics');await p.waitForFunction(()=>document.getElementById('enc-photo').naturalWidth>0);
  await p.click('#enc-listen');if(c.audio){assert.equal(c.soundEvidence,'audio');await p.waitForFunction(()=>document.getElementById('enc-audio').currentTime>.35&&document.querySelector('[data-enc-clue="sound"]').textContent.includes('已播放'));assert.match(await p.textContent('[data-enc-clue="sound"]'),/已播放/);await p.click('#enc-stop');}else{assert.equal(c.soundEvidence,'field-note');assert.match(await p.textContent('[data-enc-clue="sound"]'),/现场听记/);if(c.id==='e80')assert.match(await p.textContent('#enc-credits'),/AI 生成教学插图/);}
  await p.click('#enc-watch');const wrong=['canopy','low','ground','water','sky'].find(x=>x!==c.target);await p.click(`[data-enc-target="${wrong}"]`);assert.match(await p.textContent('#enc-predict-result'),/没有等到/);await p.click(`[data-enc-target="${c.target}"]`);assert.match(await p.textContent('#enc-predict-result'),/合适的位置/);
  for(const answer of c.resolutionCandidates||[c.answer])await p.locator('#enc-options').getByLabel(answer,{exact:true}).check();await p.click('#enc-checkpoint');await p.click('#enc-submit');assert.match(await p.textContent('#enc-review-summary'),new RegExp(c.answer));assert.match(await p.textContent('#enc-provenance'),/虚构/);
 }
 const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('avian-os.encounters.v4')));assert.equal(saved.length,11);assert.ok(saved.some(r=>r.soundMode==='audio'));assert.ok(saved.some(r=>r.soundMode==='field-note'));
 await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>getComputedStyle(document.querySelector('.enc-tracks')).gridTemplateColumns.split(' ').length),2);await p.click('#enc-track-sky');await p.click('[data-enc-case="99"]');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(engine==='chromium')await p.screenshot({path:'evidence/v6-mobile.png',fullPage:true});
 await p.goto(base+(base.includes('?')?'&':'?')+'encounter=e100');assert.match(await p.textContent('#enc-title'),/长翼/);assert.equal(await p.locator('[name="enc-answer"]').count(),11);
 if(!process.env.BASE_URL){const off=await context.newPage();off.on('pageerror',e=>errors.push(e.message));if(engine==='chromium')await context.setOffline(true);await off.goto('file://'+path.resolve('芦汀观测站.html'));if(engine==='webkit')await context.setOffline(true);await off.click('#enc-listen');await off.waitForFunction(()=>document.getElementById('enc-audio').currentTime>.35);assert.match(await off.locator('#enc-audio').getAttribute('src'),/^data:audio/);await off.click('#enc-track-raptor');await off.click('[data-enc-case="56"]');await off.click('#enc-optics');await off.waitForFunction(()=>document.getElementById('enc-photo').naturalWidth>0);assert.match(await off.textContent('#enc-credits'),/AI 生成教学插图（非真实目击照片）/);await off.click('#enc-listen');assert.match(await off.textContent('[data-enc-clue="sound"]'),/现场听记/);}
 assert.deepEqual(errors,[]);assert.deepEqual(bad,[]);fs.writeFileSync(`evidence/v7-${process.env.BASE_URL?'online':engine}.json`,JSON.stringify({passed:true,engine,url:base,scenarios:110,tracks:Object.fromEntries(Object.keys(D.tracks).map(k=>[k,D.pool(k).length])),checks:['110 unique source-backed scenes','eleven bounded tracks','attributed photos or labelled AI teaching illustrations','real recordings remain distinct from field notes','all target layers including sky','correct and wrong predictions','mobile layout','deep link','offline media'],errors,bad},null,2));await browser.close();console.log('Encounter v7 acceptance passed:',engine);
})().catch(e=>{console.error(e);process.exit(1)});
