const {chromium,webkit}=require(process.env.PLAYWRIGHT_PATH||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const D=require('../encounter-data.js');
(async()=>{
const engine=process.env.TEST_WEBKIT?'webkit':'chromium',browser=await(engine==='webkit'?webkit:chromium).launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});const p=await context.newPage(),errors=[],bad=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().includes('/assets/')&&r.status()>=400)bad.push(r.url());});
const base=process.env.BASE_URL||'http://127.0.0.1:18876/';fs.mkdirSync('evidence',{recursive:true});
await p.goto(base);assert.equal(await p.locator('#encounter-view').isVisible(),true);assert.equal(await p.locator('#challenge-view').isVisible(),false);assert.equal(await p.locator('#enc-photo').getAttribute('src'),null);assert.equal(await p.locator('#enc-photo').isVisible(),false);assert.equal(await p.locator('#enc-review').isVisible(),false);assert.equal(await p.locator('#enc-audio').evaluate(a=>a.paused),true);assert.equal(await p.locator('[data-enc-case]').count(),9);
if(engine==='chromium')await p.screenshot({path:'evidence/v5-entry.png',fullPage:true});
for(let i=0;i<D.scenes.length;i++){
 const c=D.scenes[i];if(i===9){await p.click('#enc-track-mixed');assert.equal(await p.locator('[data-enc-case]').count(),20);assert.equal(await p.locator('#enc-options input').count(),21);}await p.click(`[data-enc-case="${i}"]`);assert.equal(await p.locator('#enc-photo').getAttribute('src'),null);assert.equal(await p.locator('[data-enc-target="canopy"]').isDisabled(),true);
 // A guess may be saved before new evidence. It must not reveal the target.
 await p.locator('#enc-options').getByLabel('褐柳莺',{exact:true}).check();await p.click('#enc-checkpoint');assert.equal(await p.locator('.enc-hypothesis').count(),1);assert.equal(await p.locator('#enc-review').isVisible(),false);
 await p.click('#enc-optics');if(c.photo)await p.waitForFunction(()=>document.getElementById('enc-photo').naturalWidth>0);else {assert.equal(await p.locator('#enc-photo').getAttribute('src'),null);assert.match(await p.textContent('#enc-view-label'),/未拍到照片/);}assert.equal(await p.locator('#enc-submit').isDisabled(),true);
 await p.click('#enc-listen');await p.waitForFunction(()=>document.getElementById('enc-audio').currentTime>.5);await p.waitForFunction(()=>document.querySelector('[data-enc-clue="sound"]').textContent.includes('已播放'));assert.equal(await p.locator('#enc-submit').isDisabled(),false);
 const fft=await p.locator('#enc-spectrum').evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let count=0;for(let j=0;j<d.length;j+=4)if(d[j]>120&&d[j+1]>150)count++;return count;});assert.ok(fft>0,'actual audio spectrum');await p.click('#enc-stop');
 await p.click('#enc-watch');await p.click(`[data-enc-target="${c.target==='water'?'canopy':'water'}"]`);assert.match(await p.textContent('#enc-predict-result'),/没有等到/);assert.equal(await p.locator('[data-enc-clue="detail"]').getAttribute('class'),'enc-clue locked');
 await p.click(`[data-enc-target="${c.target}"]`);assert.match(await p.textContent('#enc-predict-result'),/合适的位置/);
 await p.locator('#enc-options').getByLabel('暂不定种',{exact:true}).check();assert.equal(await p.locator('[name="enc-answer"]:checked').count(),1);for(const name of c.resolutionCandidates||[c.answer])await p.locator('#enc-options').getByLabel(name,{exact:true}).check();assert.equal(await p.locator('[name="enc-answer"]:checked').count(),c.resolutionCandidates?.length||1);await p.click('#enc-checkpoint');assert.equal(await p.locator('.enc-hypothesis').count(),2);
 await p.fill('#enc-note','听到声音以后，结合活动高度重新预测；补充目击改变了我的猜测。');await p.click('#enc-submit');assert.match(await p.textContent('#enc-review-title'),/多条线索|保留两个候选/);assert.match(await p.textContent('#enc-review-summary'),new RegExp(c.answer));assert.match(await p.textContent('#enc-provenance'),/虚构/);assert.match(await p.textContent('#enc-review-path'),/褐柳莺/);assert.equal(await p.locator('#enc-submit').isDisabled(),true);
 if(i===0&&engine==='chromium')await p.screenshot({path:'evidence/v5-review.png',fullPage:true});
}
const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('avian-os.encounters.v4')));assert.equal(saved.length,20);assert.ok(saved.every(r=>r.correct&&r.soundMode==='audio'&&r.hypotheses.length===2));
await p.reload();assert.equal(await p.textContent('#enc-record-count'),'20');await p.click('#enc-history-button');assert.equal(await p.locator('.enc-history-entry').count(),20);await p.locator('#enc-history .close-dialog').click();
const download=p.waitForEvent('download');await p.click('#enc-export');const file=await download;const exportPath=`evidence/v5-export-${engine}.json`;await file.saveAs(exportPath);assert.equal(JSON.parse(fs.readFileSync(exportPath)).records.length,20);
// Missing a complementary observation must remain incomplete, even with the right name.
await p.click('[data-enc-case="0"]');await p.click('#enc-read-sound');await p.click('#enc-optics');await p.waitForFunction(()=>document.getElementById('enc-photo').naturalWidth>0);await p.locator('#enc-options').getByLabel('黄眉柳莺',{exact:true}).check();await p.click('#enc-submit');assert.match(await p.textContent('#enc-review-title'),/还缺/);assert.match(await p.textContent('#enc-review-path'),/文字辅助/);
// Failed audio is never recorded as heard. Text assistance remains usable.
await p.click('[data-enc-case="1"]');await p.route('**/e02-audio.mp3',r=>r.abort());await p.click('#enc-listen');await p.waitForFunction(()=>/失败|未能/.test(document.getElementById('enc-audio-status').textContent));assert.equal(await p.locator('[data-enc-clue="sound"]').getAttribute('class'),'enc-clue locked');await p.unroute('**/e02-audio.mp3');
await p.click('#enc-listen');await p.waitForFunction(()=>document.getElementById('enc-audio').currentTime>.5);await p.click('[data-tab="challenge"]');assert.equal(await p.locator('#enc-audio').evaluate(a=>a.paused),true);assert.equal(await p.locator('#challenge-view').isVisible(),true);await p.click('#track-basic');await p.click('#observe-sound');await p.waitForFunction(()=>document.getElementById('reference-recording').currentTime>.1);await p.click('[data-tab="encounter"]');assert.equal(await p.locator('#reference-recording').evaluate(a=>a.paused),true);
await p.click('[data-enc-case="0"]');await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(engine==='chromium')await p.screenshot({path:'evidence/v5-mobile.png',fullPage:true});
await p.click('#enc-read-sound');await p.click('#enc-watch');await p.click('[data-enc-target="canopy"]');await p.locator('#enc-options').getByLabel('黄眉柳莺',{exact:true}).check();await p.click('#enc-submit');assert.match(await p.textContent('#enc-review-title'),/多条线索/);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await p.goto(base+(base.includes('?')?'&':'?')+'encounter=e04');assert.match(await p.textContent('#enc-title'),/换了位置/);
// Mixed mode remains operable on a phone and does not demand a photograph.
await p.click('#enc-track-mixed');await p.click('[data-enc-case="10"]');assert.equal(await p.locator('#enc-options input').count(),21);
await p.click('#enc-optics');assert.equal(await p.locator('#enc-photo').getAttribute('src'),null);await p.click('#enc-read-sound');await p.click('#enc-watch');await p.click('[data-enc-target="low"]');
await p.locator('#enc-options').getByLabel('中华短翅蝗莺',{exact:true}).check();await p.click('#enc-submit');assert.match(await p.textContent('#enc-review-title'),/不足以排除/);
assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(engine==='chromium')await p.screenshot({path:'evidence/v5-mixed-mobile.png',fullPage:true});
await p.click('#enc-next');assert.match(await p.textContent('#enc-title'),/纵纹/);await p.click('#enc-track-leaf');assert.equal(await p.locator('[data-enc-case]').count(),9);
await p.click('[data-enc-case="8"]');await p.click('#enc-read-sound');await p.click('#enc-watch');await p.locator('#enc-options').getByLabel('暂不定种',{exact:true}).check();await p.click('#enc-submit');await p.click('#enc-next');assert.match(await p.textContent('#enc-title'),/柳梢/);
// A saved v4 record survives entering the expanded application.
const legacy=await browser.newContext();await legacy.addInitScript(()=>localStorage.setItem('avian-os.encounters.v4',JSON.stringify([{id:'e01',title:'旧版记录',candidates:['黄眉柳莺'],seen:['context','sound','detail'],answer:'黄眉柳莺',correct:true}])));const lp=await legacy.newPage();await lp.goto(base);assert.equal(await lp.textContent('#enc-record-count'),'1');await lp.click('#enc-history-button');assert.match(await lp.textContent('#enc-history-list'),/旧版记录/);await legacy.close();
if(!process.env.BASE_URL){const off=await context.newPage();off.on('pageerror',e=>errors.push(e.message));if(engine==='chromium')await context.setOffline(true);await off.goto('file://'+path.resolve('芦汀观测站.html'));if(engine==='webkit')await context.setOffline(true);await off.click('#enc-optics');await off.waitForFunction(()=>document.getElementById('enc-photo').naturalWidth>0);assert.match(await off.locator('#enc-photo').getAttribute('src'),/^data:image/);await off.click('#enc-listen');await off.waitForFunction(()=>document.getElementById('enc-audio').currentTime>.5);assert.match(await off.locator('#enc-audio').getAttribute('src'),/^data:audio/);await off.click('[data-enc-case="7"]');await off.click('#enc-listen');await off.waitForFunction(()=>document.getElementById('enc-audio').currentTime>.5);assert.match(await off.locator('#enc-audio').getAttribute('src'),/^data:audio/);}
assert.deepEqual(errors,[]);assert.deepEqual(bad,[]);const label=process.env.BASE_URL?'online':engine;fs.writeFileSync(`evidence/v5-${label}.json`,JSON.stringify({passed:true,engine,url:base,scenarios:20,checks:['environment first; no starting photo','twenty real recordings play','actual FFT','provisional hypotheses preserve evidence','photo alone cannot conclude','prediction unlocks new sighting','wrong prediction gives no false evidence','twenty evidence-appropriate resolutions','right name without detail remains incomplete','history/reload/export','failed sound not counted','text-assistance distinct from heard sound','mode switching stops both players','390px leaf and mixed flow','v4 record migration','bounded next-case navigation','ambiguous single name rejected','deep links','offline picture and real audio'],errors,bad},null,2));await browser.close();console.log('Encounter acceptance passed:',label);
})().catch(e=>{console.error(e);process.exit(1)});
