const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const D=require('../encounter-data.js');
test('twenty complete fictional encounters have licensed real sound, image and ecological sources',()=>{assert.equal(D.scenes.length,20);const credits=JSON.parse(fs.readFileSync(path.join(__dirname,'../assets/reference/credits.json')));for(const c of D.scenes){for(const k of ['area','date','time','weather','habitat','height','count','opening','sound','form','motion','detail','reason','facts'])assert.ok(c[k],c.id+' '+k);assert.ok(c.sources.length);for(const f of [c.audio,c.photo].filter(Boolean)){assert.ok(fs.existsSync(path.join(__dirname,'..',f)));const m=credits.find(x=>x.file===f);assert.ok(m&&m.author&&m.license&&m.source);if(m.license.includes('ND')){assert.equal(m.derivative,false);const hash=require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(__dirname,'..',f))).digest('hex');assert.equal(hash,m.originalSha256,'ND file must be byte-identical');}}}});
test('repeated observation does not invent independent evidence',()=>{const s=D.begin();assert.equal(D.addEvidence(s,'sound'),true);assert.equal(D.addEvidence(s,'sound'),false);assert.equal(D.addEvidence(s,'unknown'),false);assert.deepEqual(s.seen,['context','sound']);});
test('lucky correct name before complementary observations is not a supported conclusion',()=>{const c=D.scenes[0],s=D.begin();D.addEvidence(s,'form');let r=D.assess(c,s,[c.answer],'high');assert.equal(r.correct,false);assert.equal(r.verdict,'incomplete');assert.deepEqual(r.missing,['sound','detail']);D.addEvidence(s,'sound');assert.equal(D.assess(c,s,[c.answer],'high').correct,false);D.addEvidence(s,'detail');assert.equal(D.assess(c,s,[c.answer],'high').correct,true);});
test('candidate set, wrong answer and uncertainty remain distinct',()=>{const c=D.scenes[0],s=D.begin();s.seen.push('sound','detail');assert.equal(D.assess(c,s,[c.answer,'淡眉柳莺'],'low').verdict,'narrowed');assert.equal(D.assess(c,s,['巨嘴柳莺'],'high').overconfident,true);assert.equal(D.assess(c,s,[],'low').verdict,'open');});
test('intermediate hypotheses preserve the information available at the time',()=>{const s=D.begin(),choice=['褐柳莺'];D.saveHypothesis(s,choice,'low');choice.push('巨嘴柳莺');D.addEvidence(s,'sound');D.saveHypothesis(s,['巨嘴柳莺'],'medium');assert.deepEqual(s.hypotheses[0].candidates,['褐柳莺']);assert.deepEqual(s.hypotheses[0].seen,['context']);assert.deepEqual(s.hypotheses[1].seen,['context','sound']);});
test('Indian sound is not recast as a Beijing standard; all embedded assets survive offline',()=>{const c=D.scenes.find(c=>c.id==='e06');assert.match(c.area,/印度/);assert.match(c.sound,/mandellii/);const html=fs.readFileSync(path.join(__dirname,'../芦汀观测站.html'),'utf8');for(const c of D.scenes)for(const file of [c.audio,c.photo].filter(Boolean))assert.ok(html.includes(fs.readFileSync(path.join(__dirname,'..',file)).toString('base64')),file);});

test('leaf and mixed pools contain unique species, aliases are not double counted',()=>{assert.equal(D.pool('leaf').length,9);assert.equal(D.pool('mixed').length,20);assert.equal(new Set(D.scenes.map(c=>c.latin)).size,20);assert.equal(D.choices('mixed').length,20);for(const c of D.scenes){assert.ok(c.options.includes(c.answer));assert.ok(['canopy','low','ground','water'].includes(c.target));}assert.equal(D.scenes.filter(c=>c.latin==='Anthus richardi').length,1);});
test('an intentionally obscured encounter rewards the unresolved pair, not guessing the hidden author answer',()=>{const c=D.scenes.find(c=>c.id==='e11'),s=D.begin();s.seen.push('sound','detail');assert.equal(D.assess(c,s,[c.answer],'medium').correct,false);assert.equal(D.assess(c,s,c.resolutionCandidates,'medium').correct,true);assert.equal(D.assess(c,s,c.resolutionCandidates,'high').overconfident,true);});
